### ISSUE TITLE
Changing basis to my MPS/MPO implementation

### ISSUE THREAD

**Issue by dfelmanl** [block-hczhai/block2-preview#111]
Hi,

I have been working with a Julia package for solving quantum chemistry ground state problems with DMRG.

The basis it uses for the tensor trains is based on electron occupations in the molecular orbitals.

E.g. for LiH, since there are 6 molecular orbitals and 4 electrons (2 up, 2 down), the MPS's size (Hilbert space) would be $4^6$, as each of the orbitals can be occupied with four {0e, spin up, spin down, 2e} options. So the MPS would have 6 sites of size 4.

However, I am planning to restructure the basis to Slater determinants; in that way, the number of independent bases would be reduced to ${ 6 \choose 2}^2 = 225$. This would reduce the Hilbert space significantly, by only requiring 8 binary sites to represent the 225 basis states (Slater determinants).

I want to know if this is something that Block2 can help me with to import from python the OpSum to define the MPO, or any other object that I could import to Julia and formulate my problem.

Please let me know if it makes sense.

Thank you,
Daniel

**Comment by hczhai** [comment]
Hi, thanks for your interest in using ``block2``.

``block2`` supports a different variety of symmetry options. The $4^6$ case is when no symmetry group is used. Normally for quantum chemistry we use $U(1) \times U(1)$ symmetry group (``SymmetryTypes.SZ`` mode in ``block2``), for the conservation of particle number and projected spin, respectively. When the $U(1) \times U(1)$ symmetry constraint is used, the size of Hilbert space that is available to the ($S_z = 0$) MPS is already $(C^6_2)^2 = 225$.

Typically we can use even higher symmetry groups like $U(1) \times SU(2) \times PG$ (``SymmetryTypes.SU2`` mode in ``block2``) where $PG$  is the Abelian point group symmetry. Then the Hilbert space can be further reduced (to a number much smaller than 225) and the speed of DMRG will be even faster.

The idea is that when you label the target ground state with quantum numbers, such as $N_{elec} = 4, N_{up} - N_{down} = 0$, determinants like $ababab$ will be automatically excluded, because it has $N_{elec} = 6, N_{up} - N_{down} = 0$, so you will not have $4^6$ determinants here. For literature reference of the symmetry usage in quantum chemistry DMRG, see Sec. III in [_The Journal of Chemical Physics_, **136**, 124121](https://doi.org/10.1063/1.3695642). For more discussion on the symmetry modes in ``block2``, see https://block2.readthedocs.io/en/latest/tutorial/hubbard.html.

``block2`` can support reading or writing MPO/MPS tensors as ``numpy`` arrays, see https://github.com/block-hczhai/block2-preview/discussions/35. For Julia you can use the [NPZ.jl](https://github.com/fhs/NPZ.jl) package to read or write these ``numpy`` arrays.

**Comment by dfelmanl** [comment]
Thank you very much! I will review those references.
