### ISSUE TITLE
Wrong energy for large site csf 

### ISSUE THREAD

**Issue by h-larsson** [block-hczhai/block2-preview#113]
The large site CSF code may be buggy.
For the following input 
```
big_site csf !folding or disabled

mem 80 g
outputlevel 2

sym c1
orbitals FCIDUMP
nelec 17
spin 1
irrep 1

hf_occ integral
schedule default
maxM 2000
maxiter 30

nroots 1
noreorder

mrcisd 12 17
```
and enabling/disabling `big_site` or using `big_site folding` I get the following energies:
```
big_site csf                               -152.266472681059241
big_site folding                         -152.281840304144822
no big_site                                -152.281840409988433
big_site fock; nonspinadapted  -152.280601939503583
```
So it looks like the large site csf Hamiltonian misses something. The MPO bond dimensions are identical. 
FCIDUMP can be found at https://ucmerced.box.com/s/lrxv5nokl2suqnemkn9uroaps22qyy9i

**Comment by hczhai** [comment]
Thanks for reporting this problem and providing the input.

My test shows that ``big_site drt`` can produce the correct answer for this case, so if you simply need a spin-adapted big-site implementation, ``big_site drt`` is the choice (although this option is currently not listed in the documentation). It can be used with both spin-adapted and non-spin-adapted cases, for spin-adapted it is faster in construction MPO than ``big_site csf`` while for non-spin-adapted it is slower in construction MPO than ``big_site fock``.

Nevertheless, I will take a look at what happens inside ``big_site csf`` and let you know if I find something.

**Comment by hczhai** [comment]
Hi Henrik,

Unfortunately, I cannot reproduce your ``big_site csf`` energy. It also does not seem to be related to any recent commits (the one-year-ago ``block2`` code can also produce the correct energy with ``big_site csf``).

You may have a look at output from the calculation done on a Google colab notebook: https://colab.research.google.com/drive/1m2-qlcBRee9YYFn9GqxMB8yHDTySfgDN. At MPS bond dimension 500, the energy is -152.2771 (two site), which is lower than your -152.266472.

If you can reproduce this energy, sharing some information about the operating system, software environment, and output files might be helpful.

**Comment by h-larsson** [comment]
Thanks for checking this, Huanchen. I just did an additional check and it works for me if I only use one MPI process. So this issue occurs for me when using MPI parallelization, already with 2 MPI procs. Would you mind testing this with MPI on your environment? 
I use GNU 11.2.0, and openmpi 4.1.3  together with -pthread, if that is of relevance.

**Comment by hczhai** [comment]
1. Thanks for the additional hint. I can reproduce the higher energy that you observed with 2 MPI processors.
2. With 2 MPI processors, if I first use ``big_site csf`` with ``mps_tags KET1`` I get the -152.26 state, and then if I do

```
mps_tags KET2
proj_mps_tags KET1
proj_weights 0.2
```

still with 2 MPI processors to compute the 1st excited state, I get the lower -152.28 state. So it seems that the -152.26 is just an excited state, and with this FCIDUMP it is easy to get stuck in local minima. Once you get the -152.28 state, you may use ``mps_tags KET2; fullrestart`` to load this state as the initial guess without the projection to verify that its energy is correct. (So the Hamiltonian created by ``big_site csf`` should be correct.)

3. Other big site schemes like ``big_site drt`` and ``big_site folding`` can have different internal ordering for the big site, and maybe by coincidence it is slightly more difficult to converge to the wrong state with these other options. Different number of MPI processors may have something to do with the effectiveness of the noises.
4. If you load the MPS computed using ``big_site drt`` and re-compute it with ``big_site csf`` you will get a different energy, because the internal csf ordering for the big site is different. But it may still be a good initial guess because the active part gives a good environment. You may also load the state computed using 1 MPI-processor to start a 2 MPI-processor calculation.

**Comment by h-larsson** [comment]
Thanks a lot, Huanchen! Crazy that this is so subtle here. For these use cases, restricting the big site to the CAS and later expanding it might be the a good idea. Anyways, I am glad that this is not a bug in the csf construction.
