### ISSUE TITLE
Extracting observables

### ISSUE THREAD

**Issue by Shovan-Physics** [block-hczhai/block2-preview#114]
Hi, I'm struggling a little on how to extract observables from the converged state(s):

1. If I run a Heisenberg model in the `SU2` mode, how do I get the spin correlations $\langle \hat{\mathbf{S}}_i \cdot \hat{\mathbf{S}}_j \rangle$? I tried `driver.get_npdm(ket, npdm_expr="(T+T)0")` which gave all zeros. Similarly, in the `SGB` mode, it would be useful to obtain the "PM" and "ZZ" correlations, as well as one-site expectations $\langle  \hat{S}^z_i \rangle$.

2. In one of the posts you say that one can obtain the spin correlations for a Hubbard model as `driver.get_npdm(ket, pdm_type=2, npdm_expr="((C+D)2+(C+D)2)0", mask=[0, 0, 1, 1])`. Could you explain what `mask` is doing here?

3. Does `driver.get_bipartite_entanglement()` give the entanglement entropy across all bonds in the ground state? How is it different from `driver.get_bipartite_entanglement(ket)`?

4. If I am finding both the ground state and the first excited state (using `nroots=2` in the initial MPS), how do I obtain the observables in each of the two states?

It may be useful to add some of this to the documentation.

Many thanks!
Shovan

**Comment by hczhai** [comment]
1. The standard way to evaluate expectation of arbitrary operator is: first encode the terms in the operator using ``driver.expr_builder()`` and then construct the MPO using ``mpo = driver.get_mpo(...)``, then you can get the expectation of this MPO for the MPS ``ket`` using ``driver.expectation(ket, mpo, ket)``. This procedure is explained in the [documentation](https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Expectation-and-N-Particle-Density-Matrices).
2. The reason that ``driver.get_npdm`` cannot be working with ``T``, ``PM``, ``ZZ`` operators, is because these are not ``npdm`` (n-particle density matrix). A n-PDM is normally a series of strings of ``CD`` operators. Nevertheless, if you can express the ``T`` operator as ``CD`` operators, you can use ``driver.get_npdm`` to compute it. As explained in the [API documentation](https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.get_npdm), the argument ``mask`` is to label the pattern for repeated indices. Here if you omit the ``mask``, you will get ``ndim=4`` result for $\langle C_iD_jC_kD_l\rangle$ with all possible combinations of indices $ijkl$, but for spin correlation we only need $\langle C_iD_iC_jD_j\rangle$, so we use ``mask`` to restrict it to $iijj$ to save computational time.
3. For ``driver.get_bipartite_entanglement``, as explained in the [API documentation](https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.get_bipartite_entanglement), if you just finished a ``driver.dmrg`` or ``driver.expectation`` call for a given MPS ``ket``, the bipartite entanglement can be obtained for free, and in this case you do not need to set the ``ket`` argument. For some other cases, when the MPS ``ket`` is not obtained from ``driver.dmrg`` or ``driver.expectation``, you need to explicitly set the ``ket`` argument and it will cost a small amount of time to compute the bipartite entanglement. You may always set the ``ket`` argument explicitly if the efficiency is not the problem.
4. As explained in the excited state [documentation](https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Excited-States) and the [API documentation](https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.split_mps), you may use ``split_mps`` to split the ``nroots=2`` MPS to two individual MPSs, and then you can use ``driver.expectation(kets[ir], mpo, kets[ir])`` to compute the expectation value for each of them.
5. The length of the documentation cannot be arbitrarily long, otherwise the difficulty in finding any useful information in the documentation will increase, and it will waste the time of advanced users on reading/skipping unnecessary details. As a complement to the documentation, I can provide assistance for detailed procedure for specific usage cases, as long as it is within my scope of knowledge on this topic. And for this purpose the [discussion](https://github.com/block-hczhai/block2-preview/discussions) page is the right place to go.

**Comment by Shovan-Physics** [comment]
Thanks a lot for your explanation. I'm sorry for missing some parts of the documentation, which is indeed quite thorough.

Just a quick follow up: you say I can use `get_npdm` if I can express `T` in terms of the `CD` operators. As far as I understand, for the Hubbard model `T` is just `(C+D)2`. However, for the Heisenberg (`SU2`) model the `CD` operators are undefined, right? If I run `driver.get_npdm(ket, npdm_expr="((C+D)2+(C+D)2)0")` I get an IndexError. 

Of course, I can still compute the matrix $\langle \hat{\mathbf{S}}_i \cdot \hat{\mathbf{S}}_j \rangle$  by forming an `mpo` for each pair of $(i, j)$ and using `expectation`, but I was wondering if there is a more compact / faster way to do this.

**Comment by hczhai** [comment]
> However, for the Heisenberg (SU2) model the CD operators are undefined, right?

This is correct for the "general" Heisenberg model handled in https://block2.readthedocs.io/en/latest/tutorial/heisenberg.html#Introduction. In this example there is a "heis_twos" parameter. The claim ``T=(C+D)2`` is only true for the most common "spin-1/2" Heisenberg model ("heis_twos = 1"). But that code also has to deal with other Heisenberg models with a different spin at each site (such as "spin-1" Heisenberg model). As there is no well defined (fermionic) ``CD`` operators for this **any-spin** Heisenberg model case, using ``driver.get_npdm`` is invalid.

However, this does not prevent you from writing a script that can only do the spin-1/2 Heisenberg model, using the custom Hamiltonian interface, which gives you the chance to define the fermionic ``CD`` operators (which only make sense for the spin-1/2 sites), and then ``driver.get_npdm`` can work. As the spin-1/2 Heisenberg model is just a "sub-model" of the t-J model, you can slightly modify the t-J model script (which is given in the [documentation](https://block2.readthedocs.io/en/latest/tutorial/custom-hamiltonians.html#SU(2)-t-J-Model)) to do this:

```python3
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
import numpy as np

L = 100
J = 1

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SAnySU2, n_threads=4)

driver.set_symmetry_groups("U1Fermi", "SU2", "SU2")
Q = driver.bw.SX

site_basis = [[(Q(0, 0, 0), 1), (Q(1, 1, 1), 1)] for _ in range(L)]
site_ops = [{"": np.array([[1, 0], [0, 1]]), "C": np.array([[0, 0], [1, 0]]),
    "D": np.array([[0, 2**0.5], [0, 0]])} for _ in range(L)]

driver.initialize_system(n_sites=L, vacuum=Q(0, 0, 0), target=Q(L, 0, 0), hamil_init=False)
driver.ghamil = driver.get_custom_hamiltonian(site_basis, site_ops)
b = driver.expr_builder()

b.add_term("((C+D)2+(C+D)2)0", [j for i in range(L - 1) for j in [i, i, i + 1, i + 1]], J * -(3 ** 0.5) / 2)

mpo = driver.get_mpo(b.finalize(), iprint=1)
mps = driver.get_random_mps(tag="KET", bond_dim=250, nroots=1)
energy = driver.dmrg(mpo, mps, n_sweeps=10, bond_dims=[250] * 4 + [500] * 4,
    noises=[1e-4] * 4 + [1e-5] * 4 + [0], thrds=[1e-10] * 8, dav_max_iter=30, iprint=1)
print("DMRG energy = %20.15f (per site = %10.6f)" % (energy, energy / L))

spin_corr = driver.get_npdm(mps, pdm_type=2, npdm_expr='((C+D)2+(C+D)2)0', mask=(0, 0, 1, 1)) * (-(3 ** 0.5) / 4)
print(spin_corr[0, 2])

scorr_mpo = driver.get_mpo(driver.expr_builder().add_term("((C+D)2+(C+D)2)0", [0, 0, 2, 2], 1.0).finalize())
spin_corr02 = driver.expectation(mps, scorr_mpo, mps) * (-(3 ** 0.5) / 2)
print(spin_corr02)
```

Note that there is an additional 0.5 factor in ``get_npdm`` for ensuring the correct trace for particle number (in the normal N-PDM).

**Comment by Shovan-Physics** [comment]
This is great, thanks!
