### ISSUE TITLE
TDDMRG vs TDDMRG++

### ISSUE THREAD

**Issue by h-larsson** [block-hczhai/block2-preview#120]
Hi Huanchen,

The default TST algorithm in the python drivers is `RK4` which I assume is the normal TST variant. In C++ the default is `RK4PP` which I assume is the "TST++" variant  from
 http://dx.doi.org/10.1021/acs.jctc.7b00682 
Could you please confirm this? Is there a reason why the defaults are different? 

Thanks,
Henrik

**Comment by hczhai** [comment]
Hi Henrik,

The rk4 is always the original tst without ++ (corresponding to the c++ class TimeEvolution). The tst++ as described in the jctc paper was implemented as a separate c++ class TDDMRG, which is undocumented and deprecated.

**Comment by h-larsson** [comment]
Thanks for the quick answer. What is the difference between `RK4` and `RK4PP` then?

**Comment by hczhai** [comment]
RK4PP means the tst++ method, which is only checked and used inside the C++ TDDMRG class (which is undocumented).

The Python interface DMRGDriver (as implemented in core.py) never uses the class TDDMRG. Instead, it supports tdvp and original tst (enum TST), via the TimeEvolution class.

Using enum TSTPP with TimeEvolution will cause undefined behavior. But using enum TSTPP with the TDDMRG class is okay, although it is not a public feature and it is not provided as an option via the Python interface.

**Comment by hczhai** [comment]
The TDDMRG class is deprecated because (a) it needs additional "moving environment" (which makes it inconvenient to be implemented together with other TD methods) and it also comes with more overhead. (b) I do not see significant performance gain using this, when testing with some small systems. (c) the current implementation requires some filesystem feature (linking/unlinkimg tmp files) which is unavailable in Windows so it is not very portable or performance can be very different in different OS.

The unit-test still has a test for TDDMRG so it should work (if you write the Python part by yourself) but this explains why I am not adding it into the official Python interface "core.py".

**Comment by h-larsson** [comment]
Thanks for the clarification, Huanchen!
