### ISSUE TITLE
Seg fault on Hubbard dimer

### ISSUE THREAD

**Issue by ggoldsh** [block-hczhai/block2-preview#13]
Hi,

I'm trying to use block2 for DMRG as the high-level solver within some DMET calculations on the Hubbard model. As a minimal example, to compare the results with DMRG to the results with FCI, I tried to run both DMRG and FCI on a Hubbard dimer. However, block2main throws a segfault on this system. Details are below - and any help is appreciated!

The configuration file I'm using is as follows. The segfault doesn't seem to be sensitive to the schedule used. 
```
nelec 2
spin 0
hf_occ integral

schedule
0 100 1e-06 1e-06
5 200 1e-07 1e-07
8 200 1e-07 0e+00
end

maxiter 28
twodot_to_onedot 11
sweep_tol 1e-06
orbitals ./FCI_dump
warmup local_4site
nroots 1
outputlevel 2
prefix ./tmp
mkl_thrds 2
noreorder
```

The FCI_dump orbitals file is as follows:
```
&FCI NORB= 2,NELEC= 2,MS2= 0,
  ORBSYM=1,1,
  ISYM=1,
  IUHF=1,
 &END
  0.0000000000000000   0   0   0   0
  0.0000000000000000   0   0   0   0
  1.0000000000000000   1   1   1   1
  1.0000000000000000   2   2   2   2
  0.0000000000000000   0   0   0   0
 -1.0000000000000000   2   1   0   0
 -1.0000000000000000   2   2   0   0
  0.0000000000000000   0   0   0   0
 -1.0000000000000000   2   1   0   0
 -1.0000000000000000   2   2   0   0
  0.0000000000000000   0   0   0   0
  0.0000000000000000   0   0   0   0
```

With these files, when I run `block2main dmrg.conf.seg`, I get this output:
```

********************************** INPUT START **********************************
nelec                                                            2
spin                                                             0
hf_occ                                                    integral
maxiter                                                         28
twodot_to_onedot                                                11
sweep_tol                                                    1e-06
orbitals                                                ./FCI_dump
warmup                                                 local_4site
nroots                                                           1
outputlevel                                                      2
prefix                                                       ./tmp
mkl_thrds                                                        2
noreorder
schedule                  Sweep   0-   4 : Mmps =   100 Noise =     1e-06 DavTol =     1e-06
                          Sweep   5-   7 : Mmps =    10 Noise =     1e-07 DavTol =     1e-07
                          Sweep   8-  27 : Mmps =    10 Noise =         0 DavTol =     1e-07
irrep                                                            1
********************************** INPUT END   **********************************

SPIN ADAPTED - REAL DOMAIN
qc mpo type =  QCTypes.Conventional
 UseMainStack = 0 MinDiskUsage = 1 MinMemUsage = 0 IBuf = 0 OBuf = 0
 FPCompression: prec = 1.00e-16 chunk = 1024
 IMain = 0 B / 134 MB DMain = 0 B / 687 MB ISeco = 0 B / 57.2 MB DSeco = 0 B / 1.01 GB
 OpenMP = 1 TBB = 0 MKL = INTEL 2019.0.0 SeqType = Tasked MKLIntLen = 4
 THREADING = 2 layers : Global | Operator BatchedGEMM
 NUMBER : Global = 56 Operator = 28 Quanta = 0 MKL = 2
 COMPLEX = 1 KSYMM = 0
read integral finished 0.011580886999999984
integral sym error =            0
MinMPOMemUsage =  False
MPS =  CC 0 2 < N=2 S=0 PG=0 >
GS INIT MPS BOND DIMS =       1     3     1
pre-mpo memory usage =  69.7 MB
build mpo start ...
zsh: segmentation fault  block2main dmrg.conf.seg
```

Thanks for the help.
Gil

**Comment by hczhai** [comment]
Hi Gil,

Thanks for your interest in using block2. You can add the following two lines in your "dmrg.conf" to solve the problem:

    nonspinadapted
    qc_mpo_type nc

(1) Since your FCIDUMP is based on unrestricted integrals, we cannot do the default spin-adapted DMRG. Adding the keyword ``nonspinadapted`` to allow non-spin-adapted DMRG when you have the unrestricted FCIDUMP. Otherwise, when your FCIDUMP is restricted integrals, both spin-adapted and non-spin-adapted are okay and spin-adapted (default) version is faster.

(2) The two-site system is a little bit special so that some optimizations like "middle site transformation" during the MPO construction cannot work properly. You need to add the keyword ``qc_mpo_type nc`` to disable the "middle site transformation". When you have more than two sites, there is no such problem, and both the default ``qc_mpo_type auto`` and ``qc_mpo_type nc`` will be okay, and the default ``qc_mpo_type auto`` will be faster.

(3) Optionally, we suggest you add the keyword ``cutoff 0`` and setting a low davidson convergence like 1E-10 when you have < 10 sites, so that DMRG results will match more digits with the FCI results.

(4) We will add some error handling code in block2 so the error message will be more friendly when this happens.

**Comment by ggoldsh** [comment]
Thanks for the help! This clears up the issue. 

Relatedly - I'm also trying to use block2 to get excited states with DMRG, i.e. the lowest 2-5 roots. I've found a way by running `block2main` once with i.e. `nroots 2, weights 0.5 0.5` then again with those same settings plus the `statespecific` flag, and then a final time with all those settings plus the `restart_oh` flag to output the energies to an `E_oh` file.  However I'm wondering if this is the recommended approach or if there are simpler or better ways to implement this? 

Thanks!!
Gil

**Comment by hczhai** [comment]
The possible approaches for computing excited states should be quite clear in [the documentation](https://block2.readthedocs.io/en/latest/user/basic.html#state-specific-calculation). If you found that certain examples described in the documentation does not work, please let me know.
