### ISSUE TITLE
data race in mps_from_tag

### ISSUE THREAD

**Issue by mfdgroot** [block-hczhai/block2-preview#16]
Dear @hczhai,

I think there is a data race in the mps_from_tag method.
It occurs when I try to get an excited state through projection on the previous ground state.
It happens only when I use many MPI threads (~30) and it's really hard to reproduce.
The other option is that the first job has not finished writing the data, but everything happens in the same scratch dir which should have fast IO.

The output ends as follows:
```
init .. R = 1
init .. R = 1
env init finished 0.519297809980344
init .. R = 0
----- proj =   0 tag = KET1 -----
init .. R = 1
init .. R = 0
init .. R = 0
init .. R = 1
init .. R = 0
init .. R = 0
init .. R = 1
init .. R = 1
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 1
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 1
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 0
init .. R = 0
Traceback (most recent call last):
  File "/bin/Block2/p0.5.1rc2/bin/block2main", line 2161, in <module>
    xmps, xmps_info, _ = get_mps_from_tags(ipj, True, mps.center)
  File "/bin/Block2/p0.5.1rc2/bin/block2main", line 1814, in get_mps_from_tags
    smps_info.load_mutable()
RuntimeError: StateInfo::load_data on '/scratch/F.MPS.INFO.KET1-0.RIGHT.11' failed.
MPI FINALIZE: rank 17 of 30
```
The input file for the KET1 is:
```
nelec 16
spin 0
schedule
0     50  1.0000e-04  1.0000e-04
4    100  1.0000e-04  1.0000e-04
8    125  1.0000e-04  1.0000e-04
10    125  1.0000e-05  1.0000e-05
12    125  1.0000e-06  1.0000e-06
14    125  1.0000e-07  1.0000e-07
16    125  1.0000e-08  0.0000e+00
end
twodot_to_onedot 20
orbitals FCIDUMP
maxiter 100
sweep_tol 1.0000e-07
outputlevel 2
hf_occ integral
twopdm
prefix  /scratch/
mps_tags KET1
```
and for KET2:
```
nelec 16
spin 0
schedule
0     50  1.0000e-04  1.0000e-04
4    100  1.0000e-04  1.0000e-04
8    125  1.0000e-04  1.0000e-04
10    125  1.0000e-05  1.0000e-05
12    125  1.0000e-06  1.0000e-06
14    125  1.0000e-07  1.0000e-07
16    125  1.0000e-08  0.0000e+00
end
twodot_to_onedot 20
orbitals FCIDUMP
maxiter 100
sweep_tol 1.0000e-07
outputlevel 2
hf_occ integral
twopdm
prefix  /scratch/
mps_tags KET2
proj_mps_tags KET1
proj_weights 10
```

Any thoughts?

**Comment by hczhai** [comment]
Thanks for finding this issue.

(1) The mpi / reading MPS file error should be (hopefully) fixed with this commit https://github.com/block-hczhai/block2-preview/commit/ca04e60494b5fa03acd31daa98d0bef1ee2c76b9 and the new version tag is [p0.5.1rc3](https://github.com/block-hczhai/block2-preview/releases/tag/p0.5.1rc3). Please let me know whether this actually solves your problem.

(2) Your output shows another problem in the (unofficial) version p0.5.1rc2, which is that the all mpi processors are printing into the standard output, and this makes the output hard to read. In the version v0.5.0 there was no such problem. Now this output problem should be fixed in p0.5.1rc3 after this commit https://github.com/block-hczhai/block2-preview/commit/5b4a96d239c7566efe4ebe455ec5495231ac6d12.

(3) In practice, for efficiency considerations we do not recommend using too many mpi processors for small or medium sized systems (if you are using only one node). Since you are not using ``num_thrds`` keyword (for shared memory parallelism) in your input file, every mpi processor uses only one CPU core. Ideally, if you set ``num_thrds 30`` in your input file, and using only one mpi processor, you will see that the calculation can run much faster (assuming you have 30 cores in one node).

**Comment by mfdgroot** [comment]
Hi @hczhai,
Thanks for the quick response.
I was testing rc3 and ran into the following error:
```
TypeError: Unregistered type : std::vector<std::vector<long double, std::allocator<long double> >, std::allocator<std::vector<long double, std::allocator<long double> > > >

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apps/prod/QCLAB/Block2/p0.5.1rc3/bin/block2main", line 2201, in <module>
TypeError: Unregistered type : std::vector<std::vector<long double, std::allocator<long double> >, std::allocator<std::vector<long double, std::allocator<long double> > > >

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apps/prod/QCLAB/Block2/p0.5.1rc3/bin/block2main", line 2201, in <module>
    for x in dmrg.energies:
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: block2.su2.DMRG) -> std::vector<std::vector<long double, std::allocator<long double> >, std::allocator<std::vector<long double, std::allocator<long double> > > >

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
    for x in dmrg.energies:
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: block2.su2.DMRG) -> std::vector<std::vector<long double, std::allocator<long double> >, std::allocator<std::vector<long double, std::allocator<long double> > > >

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```
Probably just a forgotten include somewhere as the error suggests.

With respect to (3): I used this configuration because Stackblock was better at exploiting MPI threading than OpenMP and the recommendation there was to use as many MPI threads as possible. Is this now different for Block2?

**Comment by hczhai** [comment]
Sorry, the error was due to a change in another feature unrelated to this issue, and it is fixed in [p0.5.1rc4 (temporary)](https://github.com/hczhai/block2-preview/releases/tag/p0.5.1rc4) or [p0.5.1rc4](https://github.com/block-hczhai/block2-preview/releases/tag/p0.5.1rc4) (will be available in a few hours).

For (3), according to https://sanshar.github.io/Block/with-pyscf.html?highlight=num_thrds#parallelism, it was suggested that ``num_thrds`` is more efficient. Could you let me know where did you get the information that MPI in StackBlock is more efficient? Nevertheless, both OpenMP and MPI parallelism are implemented differently in Block2 and Stackblock, so in principle they are separate problems.

In practice, however, I have indeed heard that StackBlock OpenMP can be very slow if it was compiled in the wrong way. If this is the case, you can also try the pre-compiled StackBlock binaries (https://github.com/hczhai/StackBlock/releases/tag/v1.5.3) using ``pip install``.

**Comment by mfdgroot** [comment]
Thanks, the rc4 version works.

I agree with your conclusion from Sandeep's documentation about parallelism.
It seems I remembered wrongly, no clue why.
