### ISSUE TITLE
pip installation is not working 

### ISSUE THREAD

**Issue by sherrylixuecheng** [block-hczhai/block2-preview#18]
Hello block2 developers,

I'm trying to install block2 using ``pip`` but it is stuck at the building wheel step for over an hour. My python version is 3.9.12. Here are the printout lines:

``Collecting block2 ``
``  Using cached block2-0.5.0.tar.gz (762 kB) ``
 `` Preparing metadata (setup.py) ... done``
``Requirement already satisfied: mkl==2019 in /opt/anaconda3/lib/python3.9/site-packages (from block2) (2019.0)``
``Requirement already satisfied: mkl-include in /opt/anaconda3/lib/python3.9/site-packages (from block2) (2022.1.0)``
``Requirement already satisfied: intel-openmp in /opt/anaconda3/lib/python3.9/site-packages (from block2) (2022.1.0)``
``Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.9/site-packages (from block2) (1.21.5)``
``Requirement already satisfied: cmake==3.17 in /opt/anaconda3/lib/python3.9/site-packages (from block2) (3.17.0)``
``Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.9/site-packages (from block2) (1.8.0)``
``Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.9/site-packages (from block2) (5.8.0)``
``Requirement already satisfied: pybind11 in /opt/anaconda3/lib/python3.9/site-packages (from block2) (2.10.0)``
``Building wheels for collected packages: block2``
``  Building wheel for block2 (setup.py) ... |``
Not sure the exact issue here since there is no printout to show the building process. I would appreciate if someone could take a look at the pip installation binary. 

I also tried the ``pip install block2 --no-binary block2``, and it also encounters the same issue. 

``Skipping wheel build for block2, due to binaries being disabled for it.``
``Installing collected packages: block2``
``  Running setup.py install for block2 ... ``

I'm aware of the alternative manual installation way and trying that now. Just hope to report this issue to you. Thank you for your time and help!
Best,
Sherry

**Comment by hczhai** [comment]
Thanks for reporting the issue.

In the pip installation process, it will first check your operating system and python version, etc. If your operating system and python version meet some conditions, it will download the corresponding precompiled binaries and the whole ``pip install`` command will finish in a few seconds. However, if your system environment does not meet the conditions, the only choice is downloading the source and compile it from source. This is what "Building wheel for block2 (setup.py) ..." is doing. Normally you may need at least 10 GB memory and 30 min to 2 hours to compile it if you only have a few CPU cores. Sometimes the compilation process can even fail, if the compiler in your system is too old (or too new), etc.

> I would appreciate if someone could take a look at the pip installation binary.

When "Building wheel for block2 (setup.py) ..." appears, it means that pip is not using any binaries.

> I also tried the ``pip install block2 --no-binary block2``.

For your case, since no suitable binaries can be used, ``pip install block2 --no-binary block2`` has exactly the same effect as ``pip install block2``.

> I'm aware of the alternative manual installation way and trying that now.

If you try manual installation (building from source), it will also take hours (but maybe shorter because you can disable some unnecessary options).

Ideally we do not want the user to spend too long on compiling the code. **Could you let me know what is your operating system? If it is MacOS, is it with Intel CPU or Apple CPU?** If possible we can provide binaries for a large variety of different cases so that ``pip`` can always find the suitable binaries and the long compiling process can be skipped.

**Comment by sherrylixuecheng** [comment]
Thank you so much for your quick reply! It makes sense now. My operating system is **MacOS with Intel CPU**. Also, thx for providing the estimated compilation time!

**Comment by hczhai** [comment]
Thanks for providing the operating system information. I guess maybe you are using MacOS version 10? If this is true:

The current block2 (version 0.5.0) binary supports MacOS 11 (Big Sur) and MacOS 12 (Monterey), but not MacOS 10. Of course you can always compile form source and your manually compiled binary can still run in that old MacOS.

Alternatively, you can try an older version of block2 ``pip install block2==0.4.8`` and this can support MacOS 10.15 and no compiling is needed.

**Comment by sherrylixuecheng** [comment]
My laptop's operating system is MacOS 12.4, and it is wired that block2 cannot directly be installed. No worries~ I have successfully installed using ``pip install block2==0.4.8``
