### ISSUE TITLE
DMRG calculation for open shell species in active space

### ISSUE THREAD

**Issue by mariomotta** [block-hczhai/block2-preview#2]
Greetings,

I have been trying to run some basic DMRG calculations for a small open-shell molecule, namely OH, in an active space. Unfortunately I am encountering some issues, documented below, and would be grateful if you could please help me understand and overcome them. The script I use to generate the 'fcidump.txt' is below and the fcidump file is enclosed,

>>>>>>
from functools import reduce
import numpy
from pyscf import gto,scf,ao2mo,mcscf
from pyscf import symm
from pyscf.tools import fcidump

mol = gto.M(atom     = [['O',(0,0,0)],
                        ['H',(0,0,1)]],
            basis    = 'sto-6g',
            verbose  = 4,
            symmetry = 'c2v',
            spin     = 1)

myhf = scf.ROHF(mol)
myhf.kernel()
myhf.analyze()

c = myhf.mo_coeff[:,2:]
mc = mcscf.CASCI(myhf,c.shape[1],(3,2))
h1e,ecore = mc.get_h1cas()
eri = ao2mo.restore(8,mc.get_h2cas(),mc.ncas)

fcidump.from_integrals('fcidump.txt',h1e,eri,mc.ncas,5,nuc=ecore,ms=1)
<<<<<<

the dmrg.conf file is below,

>>>>>>
sym                                                             c1
orbitals                                               fcidump.txt
nelec                                                            5 
spin                                                             1
irrep                                                            1
hf_occ                                                    integral
schedule default
maxM 500
<<<<<<

but the calculation returns an energy higher than the HF value. Could you please help me understand why?

Many thanks,
Mario 

[fcidump.txt](https://github.com/block-hczhai/block2-preview/files/7457662/fcidump.txt)
[error.txt](https://github.com/block-hczhai/block2-preview/files/7457661/error.txt)

**Comment by hczhai** [comment]
Thanks for pointing out this issue.

For some tiny systems, the default initial guess and/or orbital ordering may make the dmrg calculation stuck in local minima. There are a few ways to solve this problem.

(1) The HF energy is -75.0773765977203. Your input files gives (using block2) -74.862515045991501. This is actually the energy of an excited state. We can revise the input to compute 4 roots (state-averaged):

    sym c1
    orbitals fcidump.txt
    irrep 1
    schedule default
    maxM 500
    nroots 4

You will see the energy for the lowest four states:
E[  4] =     -75.0955644681    -75.0955644674    -74.8625147323    -74.6600112451

Now the ground state energy should be correct. And the previous result is the 3rd excited state.

(2) For this input file, if I use StackBlock, I get the correct energy -75.095564196667 . This is because StackBlock and block2 use different default initial guess. StackBlock initial guess works better for HF orbitals. We can also use occupation number to construct the HF initial guess in block2:

    sym c1
    orbitals fcidump.txt
    irrep 1
    schedule default
    maxM 500
    warmup occ
    occ 2 2 1 0

Now I get the ground state energy as -75.095564454265642. Which should be correct.
Note, however, for practical computations, the occ should include some noise, so something like "occ 1.9 1.9 1.1 0.1" might be better. Or "occ 2 2 1 0; cbias 0.1" will have the same effect. See https://block2.readthedocs.io/en/latest/user/keywords.html for details.
Normally, using the diagonal elements of 1pdm of CCSD or MP2 as occ to construct DMRG initial guess is a good choice.

(3) For this example, avoid orbital reordering can also help. Adding "noreorder" in the input:

    sym c1
    orbitals fcidump.txt
    irrep 1
    schedule default
    maxM 500
    noreorder

With this input I get -75.095563651427540.

(4) Adding the keyword "nonspinadapted" can also give you the correct energy. But this may be slower and the solution may not have the correct total spin in some cases.

(5) Adding the keyword "full_fci_space" can also give you the correct energy. What this keyword does is a little bit technical. The "FCI" space used in the StackBlock code is slightly larger than the "FCI" of block2. But those extra parts are redundant. Maybe this extra redundant parametrization of FCI space can help introducing some randomness in the initial guess and in the first sweep, which helps avoiding converging to local minima.
The keyword  "full_fci_space" tells block2 to use the same redundant FCI space as StackBlock. This can slightly slow down the first sweep. In practice, the difference in speed is negligible.

**Comment by mariomotta** [comment]
Thank you very much, it works exactly as you described.
Many apologies for leaving the issue open, 
I didn't notice there had been no reply.
