### ISSUE TITLE
State specific dmrgci orbitals for multiple roots in pyblock2

### ISSUE THREAD

**Issue by leochaussy** [block-hczhai/block2-preview#27]
Hello,

I would like to retrieve the natural orbitals for each state following a state-averaged dmrgscf calculation. As I understood, a second DMRGCI should be performed on the averaged density to get a set of orthogonal orbitals. Is it currently possible via pyblock2 or the only option is to use the "statespecific" keyword via block2main as described in the documentation ? Alternatively, I suppose I can just follow up that procedure and diagonalise the 1pdm for each state but I also have to do the previous state-averaged calculation with block2main (not via pyblock2) ?

Any advice most welcome

**Comment by hczhai** [comment]
Thanks for your interest in ``block2``.

When you say "via pyblock2", do you mean
(a) ``pyscf.dmrgscf`` (following the documentation https://block2.readthedocs.io/en/latest/user/dmrg-scf.html;
or (b) using ``pyblock2/dmrgscf.py``?

**Comment by leochaussy** [comment]
I am indeed not using pyblock2 but pyscf.dmrgscf similarly as to what was proposed in the doc for state-average calculations.

**Comment by hczhai** [comment]
Thanks for the clarification of the question. Since you are using the ``pyscf.dmrgscf`` interface (the other option ``pyblock2/dmrgscf.py`` is for experimental purpose and not recommended), you can use the ``mc.fcisolver.states_make_rdm1`` method provided in ``pyscf`` to get the 1pdm for each individual state.

The following is an example script. Note that this is a feature of ``pyscf`` not ``block2``. So you can run the following script with or without DMRG, by changing the variable ``use_dmrg``.

First we do the state-average CASSCF for three states.

```python
from pyscf import gto, scf, lib, mcscf, dmrgscf
import numpy as np
import os

use_dmrg = False

if use_dmrg:
    dmrgscf.settings.BLOCKEXE = os.popen("which block2main").read().strip()
    dmrgscf.settings.MPIPREFIX = ''
    lib.param.TMPDIR = os.path.abspath('./tmp')
    if not os.path.exists(lib.param.TMPDIR):
        os.mkdir(lib.param.TMPDIR)

mol = gto.M(atom='C 0 0 0; C 0 0 1.2425', basis='ccpvdz',
    symmetry=False, verbose=4, max_memory=10000) # mem in MB
mf = scf.RHF(mol)
mf.kernel()

mc = mcscf.CASSCF(mf, 8, 8)

if use_dmrg:
    mc.fcisolver = dmrgscf.DMRGCI(mol, maxM=500, tol=1E-10)
    mc.fcisolver.runtimeDir = lib.param.TMPDIR
    mc.fcisolver.scratchDirectory = lib.param.TMPDIR
    mc.fcisolver.threads = 8
    mc.fcisolver.memory = int(mol.max_memory / 1000) # mem in GB

mc.fcisolver.conv_tol = 1E-10
if not use_dmrg:
    mc.fix_spin_(ss=0)
mc = mcscf.addons.state_average(mc, np.ones((3, )) / 3)
mc.canonicalization = True
mc.natorb = True
mc.kernel()

dms = mc.fcisolver.states_make_rdm1(mc.ci, mc.ncas, mc.nelecas)
```

Then we can find the natural orbital coefficients by diagonalizing the 1pdm for each state:

```python
state_nat_coeffs = [None] * 3
for i in range(3):
    u = np.linalg.eigh(dms[i])[1]
    state_nat_coeffs[i] = mc.mo_coeff.copy()
    state_nat_coeffs[i][:, mc.ncore : mc.ncore + mc.ncas] = state_nat_coeffs[i][:, mc.ncore : mc.ncore + mc.ncas] @ u
```

**Comment by leochaussy** [comment]
Thank you that was just what i needed !
