### ISSUE TITLE
Cannot find "DataFrame" in the codes

### ISSUE THREAD

**Issue by Eureka10shen** [block-hczhai/block2-preview#33]
I want to reproduce works in https://block2.readthedocs.io/en/latest/developer/mpo-reloading.html for "MPO reloading".
But when executing the codes of "Saving a Serial MPO" part, there came the error reported as "NameError: name 'DataFrame' is not defined" for line 8.
Could you help solve this problem?

**Comment by hczhai** [comment]
Thanks for reporting the issue.

You can solve the problem by changing ``DataFrame`` to ``DoubleDataFrame``. This is caused by an API change between the new and old versions of ``block2``. I have updated the documentation page in this commit to fix this: https://github.com/block-hczhai/block2-preview/commit/9333a1724f88b6e698004c40bff3dadd6b4e38d6

**Comment by Eureka10shen** [comment]
> Thanks for reporting the issue.
> 
> You can solve the problem by changing `DataFrame` to `DoubleDataFrame`. This is caused by an API change between the new and old versions of `block2`. I have updated the documentation page in this commit to fix this: [9333a17](https://github.com/block-hczhai/block2-preview/commit/9333a1724f88b6e698004c40bff3dadd6b4e38d6)

It works. Thank you very much !!!
