### ISSUE TITLE
How to output the MPO in the tensor form ?

### ISSUE THREAD

**Issue by Eureka10shen** [block-hczhai/block2-preview#34]
As I learned, the MPO is the product of a series of 3 or 4 way tensor (every site with a tensor).
I can only output the MPO in the "mpo.bin" file following https://block2.readthedocs.io/en/latest/developer/mpo-reloading.html.
So can we get the MPO in a more explicit way where the outputs are tensors for n_orb sites ?
Or can the "mpo.bin" file be transformed to it ?
Thank you very much !!!
(The goal I want to reach is to directly get the energy scalar by contracting the random MPS tensors with the MPO tensors.)

**Comment by hczhai** [comment]
Hi, thanks for your interest in using ``block2``.

As ``block2`` is developed for very large scale calculations, the internal data structure of MPO is more complicated than a 4-leg tensor. In ``block2`` every MPO tensor is represented as a matrix of matrices. The outer matrix is a element-wise-sparse matrix of symbols. Then every symbol is linked to a block-sparse matrix (the inner matrix). Also we do not have a trivial function to directly contract any MPS tensor with any MPO tensor because for a medium-size quantum chemistry (~ 40 orbitals) problem such a two-tensor contraction will be too expensive.

However, we understand that for small scale quantum chemistry problems, or for educational purposes, it would be convenient to expose the conventional tensor representation of MPS and MPO and provide easy functions to manipulate them. For this purpose you may have a look at another repo that we have developed: https://github.com/block-hczhai/pyblock3-preview . In ``pyblock3`` you can easily print every tensor in an MPO and the contraction can be done using simply ``mpo @ mps``. The code of ``pyblock3`` is also much shorter and easier to understand.

**Comment by Eureka10shen** [comment]
> Hi, thanks for your interest in using `block2`.
> 
> As `block2` is developed for very large scale calculations, the internal data structure of MPO is more complicated than a 4-leg tensor. In `block2` every MPO tensor is represented as a matrix of matrices. The outer matrix is a element-wise-sparse matrix of symbols. Then every symbol is linked to a block-sparse matrix (the inner matrix). Also we do not have a trivial function to directly contract any MPS tensor with any MPO tensor because for a medium-size quantum chemistry (~ 40 orbitals) problem such a two-tensor contraction will be too expensive.
> 
> However, we understand that for small scale quantum chemistry problems, or for educational purposes, it would be convenient to expose the conventional tensor representation of MPS and MPO and provide easy functions to manipulate them. For this purpose you may have a look at another repo that we have developed: https://github.com/block-hczhai/pyblock3-preview . In `pyblock3` you can easily print every tensor in an MPO and the contraction can be done using simply `mpo @ mps`. The code of `pyblock3` is also much shorter and easier to understand.

Got it. Thank you for your help!!!
