### ISSUE TITLE
ImportError for newer pybind11 versions

### ISSUE THREAD

**Issue by h-larsson** [block-hczhai/block2-preview#36]
Hi Huanchen,

It looks like Pybind Version >= 2.10.2 introduces the error 
```
ImportError: generic_type: cannot initialize type "KeysView[Tuple[str, int]]": an object with that name is already defined
```

Which seems to be due to https://github.com/pybind/pybind11/pull/4353
Do you have an idea how to fix this?

**Comment by hczhai** [comment]
Yes that's why I restricted the version number here: https://github.com/block-hczhai/block2-preview/blob/master/setup.py#L170
I will have a look at the link and see if I can fix it.

**Comment by hczhai** [comment]
Hi, I think this is a bug introduced in ``pybind11==2.10.2`` due to the pull request you mentioned, and it is not solved even in the newest version ``pybind11==2.10.4``. You can get the error using the following minimal example:

```C++
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl_bind.h>
#include <map>
#include <string>

namespace py = pybind11;
using namespace std;

PYBIND11_MODULE(xtest, m) {
    m.doc() = "xtest.";
    py::bind_map<map<int, int>>(m, "xx");
    py::bind_map<map<long long int, int>>(m, "yy");
}
```

Save this file as ``xtest.cpp`` and you can compile it using

```bash
g++ -O3 -Wall -shared -std=c++11 -fPIC $(python3 -m pybind11 --includes) xtest.cpp -o xtest$(python3-config --extension-suffix)
```

And then if you do ``python -c 'import xtest'`` you get the following

```bash
ImportError: generic_type: cannot initialize type "KeysView[int]": an object with that name is already defined
```

Now if you change the two lines to
```C++
    py::bind_map<map<int, double>>(m, "xx");
    py::bind_map<map<long long int, int>>(m, "yy");
```

You get even strange warnings at compile time. So there is nothing I can do to fix this. Let's just give up the version ``>=2.10.2``.

**Comment by hczhai** [comment]
This is basically https://github.com/pybind/pybind11/issues/4529

**Comment by h-larsson** [comment]
Thanks for checking this. Hopefully they will resolve it soon.

**Comment by Tobias-Fischer** [comment]
Have you found a workaround for this?

**Comment by hczhai** [comment]
@Tobias-Fischer @h-larsson The issue was fixed in https://github.com/pybind/pybind11/pull/4985.
