### ISSUE TITLE
Symmetry related problem with compressed DMRG-SC-NEVPT2

### ISSUE THREAD

**Issue by qiuyunze** [block-hczhai/block2-preview#42]
I'm trying to carry out compressed DMRG-SC-NEVPT2 calculation on a symmetrized Fe-Porphyrin with active space (11o, 8e). I encountered an error related to symmetry during NEVPT2 process. Could you please help me with this problem?
`Traceback (most recent call last):
  File "/hpc-cache-pfs/ailab/qiuyunze//venv/python38/bin//block2main", line 3555, in <module>
    pmpo.build()
RuntimeError: Hamiltonian may contain multiple total symmetry blocks (small integral elements violating point group symmetry)!
Traceback (most recent call last):
  File "/hpc-cache-pfs/ailab/qiuyunze/venv/python38/lib/python3.8/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 509, in <module>
    nevpt_integral_mpi(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "/hpc-cache-pfs/ailab/qiuyunze/venv/python38/lib/python3.8/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 306, in nevpt_integral_mpi
    f = open(os.path.join(nevpt_scratch_mpi, 'node0', 'Va_%d'%root), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/hpc-cache-pfs/ailab/qiuyunze/work/FePor_no_simplified/DMRG_11o_8e/nevpt2_1/node0/Va_0'`

**Comment by hczhai** [comment]
Thanks for reporting the problem. I assume that this only happens when you used point group symmetry.
Please update the code according to this commit: https://github.com/block-hczhai/block2-preview/commit/f591fd0e159b7fddc1fd228ba539ffabc6dfa803

Then, in your NEVPT2 python script, you can add an extra keyword using (for example) ``mc.fcisolver.block_extra_keyword = ['nevpt_symmetrize_ints 1E-10']``

You can increase the cutoff ``1E-10`` (which will delete some small elements in the integral) until the error disappear. The default is ``1E-12``. In general any number < ``1E-7`` is okay.

**Comment by hczhai** [comment]
Fixed by https://github.com/block-hczhai/block2-preview/commit/ff6107dcd9ce44c6435619d367f0609e86d77a0e.
