### ISSUE TITLE
ltdmrg.py cannot import "get_partition_weights" 

### ISSUE THREAD

**Issue by sunchong137** [block-hczhai/block2-preview#43]
I recently installed block2 via `pip install block2`, and then tried to run `ltdmrg.py` in  `pyblock2`, it seems the module `get_partition_weights` cannot be imported:

`ImportError: cannot import name 'get_partition_weights' from 'block2'`

**Comment by hczhai** [comment]
Hi Chong,

Thanks very much for reporting this issue.
The problem should now be fixed in https://github.com/block-hczhai/block2-preview/commit/1864dca531bcd7a0f5de396c32d9f3704a01c6af, please try the newest source code or use ``pip install block2==0.5.2rc7 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/``.
Let me know if there are any further problems.
