### ISSUE TITLE
Transition Density Matrices with state_average_mix?

### ISSUE THREAD

**Issue by dking072** [block-hczhai/block2-preview#49]
Hello,

I am trying to calculate transition density matrices between states in different irreps using state_average_mix in PySCF (e.g. see here: https://block2.readthedocs.io/en/latest/user/dmrg-scf.html for the energy calculation)

Averaging over two irreps appears to create two separate scratch directories and run directories ("solver0" and "solver1") each with their own dmrg.conf input with the respective # of roots in specified in each passed fcisolver.

I am now trying to calculate transition density matrices between the computed ground state (e.g. in the 1A1 irrep) and a number of computed excited states (e.g. in the 1B1 irrep), following the documentation here: https://block2.readthedocs.io/en/latest/user/basic.html#note1

There is some suggestion of this in the documentation, which states:

"""
The transition density matrices between states with different point group irreducible representations are also available by simply adding the keyword tran_twopdm after the corresponding multi-target state-averaged calculation.
"""

But adding this keyword to either dmrg.conf and then running does not interact at all with the other irrep. I have tried to find a workaround by post-hoc "tagging" the matrices by renaming the files / doing follow-up state specific calculations in the excited state irrep and then following the info in the "Load MPS for Density Matrix Calculation" of the documentation, but I have run into several issues trying to work this approach as well.

Is there any official supported method for computing transition density matrices from state_average_mix?

Thanks,

-Daniel

**Comment by hczhai** [comment]
Hi Daniel,

Thanks for pointing out the issue. As you have noticed, the computation of transition PDM requires that the two MPSs be in the same scratch folder but with different tags. But when you do ``state_average_mix``, the storage of MPS is not organized in this way, and simple "copy and paste" will not solve the problem because you have to also change the "tag" (you can change the ``tag`` using ``restart_copy_mps`` keyword but this workflow will be a little bit too complicated). I cannot control how ``state_average_mix`` is implemented since it is not part of ``block2``. But after a converged CASSCF, you can always use the converged ``mc.mo_coeff`` to generate the integrals (saved in FCIDUMP, for example), then regenerate the MPSs (by recomputing the DMRG) in the correct way using the ``block2`` input file as explained in the ``Basic Usage`` documentation, and then it should work. You also need the ``conventional_npdm`` keyword, otherwise there can be some problem.

The following is a (alternative) pure python script to do this without the need to manipulate input files:

```python3
import block2
from pyscf import gto, scf, lib, dmrgscf, mcscf
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyblock2._pyscf.ao2mo import integrals as itg
import numpy as np
import os

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, stack_mem=4 << 30, n_threads=8)
dmrgscf.settings.BLOCKEXE = os.popen("which block2main").read().strip()
dmrgscf.settings.MPIPREFIX = ''

lib.param.TMPDIR = os.path.abspath(driver.scratch)

if not os.path.exists(lib.param.TMPDIR):
    os.mkdir(lib.param.TMPDIR)
    
mol = gto.M(atom='C 0 0 0; C 0 0 1.2425', basis='cc-pvdz', symmetry='d2h', verbose=4)
mf = scf.RHF(mol).run()

solvers = [dmrgscf.DMRGCI(mol, maxM=1000, tol=1E-10) for _ in range(2)]
weights = [1.0 / len(solvers)] * len(solvers)

# 0   1   2   3   4   5   6   7   8   (MOLPRO convention)
# --- A1g B3u B2u B1g B1u B2g B3g A1u

# 0   1   2   3   4   5   6   7   8   (XOR convention)
# A1g B1g B2g B3g A1u B1u B2u B3u ---

solvers[0].wfnsym = 1 # A1g (MOLPRO convention)
solvers[1].wfnsym = 6 # B2g (MOLPRO convention)

for i, mcf in enumerate(solvers):
    mcf.runtimeDir = lib.param.TMPDIR + "/%d" % i
    mcf.scratchDirectory = lib.param.TMPDIR + "/%d" % i
    mcf.threads = 8
    mcf.memory = int(mol.max_memory / 1000) # mem in GB

mc = mcscf.CASSCF(mf, 8, 8)
mcscf.state_average_mix_(mc, solvers, weights)

mc.canonicalization = True
mc.natorb = True
mc.kernel()

mf.mo_coeff = mc.mo_coeff

ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf, mc.ncore, mc.ncas, g2e_symm=8)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)
driver.write_fcidump(h1e, g2e, ecore=ecore, filename='./FCIDUMP', pg="d2h", h1e_symm=True)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=0)

target = driver.bw.SX(n_elec, spin, 0) # A1g (XOR convention)
ket0 = driver.get_random_mps(tag="KET0", bond_dim=500, nroots=1, target=target)
energy = driver.dmrg(mpo, ket0, n_sweeps=10, bond_dims=[500] * 10, noises=[1e-5] * 4 + [0],
    thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
print('CASCI/DMRG energy (A1g) = %20.15f' % energy)

target = driver.bw.SX(n_elec, spin, 2) # B2g (XOR convention)
ket1 = driver.get_random_mps(tag="KET1", bond_dim=500, nroots=1, target=target)
energy = driver.dmrg(mpo, ket1, n_sweeps=10, bond_dims=[500] * 10, noises=[1e-5] * 4 + [0],
    thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
print('CASCI/DMRG energy (B2g) = %20.15f' % energy)

dm1 = driver.get_conventional_1pdm(ket=ket0, bra=ket1)
np.set_printoptions(precision=3)
print('Transition 1PDM (B2g <- A1g) =\n', dm1)
```

Note that the recomputed DMRG energy should match the CASSCF results. Each MPS must have a different tag.

**Comment by dking072** [comment]
Thanks! I am not doing CASSCF though (just DMRGCI) so it seems like it would be better to just use this more expressive python interface directly rather than the DMRGSCF code.

However, if I want to compute multiple states in one irrep (e.g. nroots > 1 in ket1) and then compute the TDM between the ground state and the different computed excited states is that possible? Furthermore, how does / can one do state specific DMRG in the python interface?

**Comment by dking072** [comment]
I am also still unclear on how this would be done using the input file interface. Doing sa_mix with e.g. 1 A1 state and 2 B1 states gives the following input files (ignore the small M value):

A1 Irrep (solver0):

"""
nelec 10
spin 0
irrep 1
schedule
0     20  1.0000e-04  1.0000e-04
2     20  1.0000e-05  1.0000e-05
4     20  1.0000e-06  1.0000e-06
6     20  1.0000e-07  1.0000e-07
8     20  1.0000e-08  0.0000e+00
end
twodot_to_onedot 12
sym c2v
orbitals FCIDUMP
maxiter 20
sweep_tol 1.0000e-07
outputlevel 2
hf_occ integral
twopdm
prefix  /path/to/scrdir/solver0
memory, 60, g
num_thrds 24
singlet_embedding
symmetrize_ints 10
onepdm
"""

B1 irrep:

"""
nelec 10
spin 0
irrep 2
schedule
0     20  1.0000e-04  1.0000e-04
2     20  1.0000e-05  1.0000e-05
4     20  1.0000e-06  1.0000e-06
6     20  1.0000e-07  1.0000e-07
8     20  1.0000e-08  0.0000e+00
end
twodot_to_onedot 12
sym c2v
orbitals FCIDUMP
maxiter 20
sweep_tol 1.0000e-07
outputlevel 2
hf_occ integral
twopdm
prefix  /path/to/scrdir/solver1
nroots 2
weights 0.500000 0.500000
memory, 60, g
num_thrds 24
singlet_embedding
symmetrize_ints 10
onepdm
"""

I understand that the problem is that they use separate scratch directories, but what exactly would need to be modified in these input files to calculate the transition density matrices? Would I need to change the "prefix" argument to give them the same scratch directory and run them one-by-one, with "mps_tags" and then do "restart_tran_onepdm"? But the mps_tags approach seems to have issues when I have multiple states, so would I need to first do state-specific calculations with separate mps_tags in the same scratch and then do an additional "restart_tran_onepdm"?

**Comment by hczhai** [comment]
### General considerations

> I am not doing CASSCF though (just DMRGCI) so it seems like it would be better to just use this more expressive python interface directly rather than the DMRGSCF code.

If you are just doing DMRGCI, then ``state_average_mix`` is not very relevant. The purpose of ``state_average_mix`` is to find a common orbital ``mc.mo_coeff`` for states with different spins or irreps. But you do not want to optimize orbitals.

> Additionally, are keywords such as "singlet_embedding" supported by the python interface?

Your input has "spin 0" so "singlet_embedding" will have no effect. The python interface uses "singlet_embedding" by default and you can disable it using ``driver.initialize_system(..., singlet_embedding=False)``.

### Using the input file interface (simple case)

The statement in the documentation that you quoted: "The transition density matrices between states with different point group irreducible representations are also available by simply adding the keyword tran_twopdm after the corresponding multi-target state-averaged calculation." is for the **multi-target** style of the state-averaged calculation, and this means that you compute states with two or more irreps in a single DMRG state-averaged calculation. Note that if you run through "pyscf/dmrgscf" interface, it will not use the **multi-target** style because it is not support in ``StackBlock`` program and the "pyscf/dmrgscf" interface is designed for the ``StackBlock`` program.

In a multi-target state-averaged calculation, you put multiple numbers for the ``irrep`` and/or ``spin`` and/or ``nelec`` keywords. Then if ``nroots = 5``, the DMRG will try to find the 5 lowest states. You may get 3 states with ``irrep 1`` and 2 states with ``irrep 2``, or you may get only 5 ``irrep 1`` states if all ``irrep 2`` states are too high in energy. In this mode you cannot control the number of states for every individual quantum number. An example input file is:

```
irrep 1 2
nroots 5
schedule default
maxM 500
sym d2h
orbitals FCIDUMP
maxiter 20
sweep_tol 1E-8
num_thrds 28
tran_onepdm
conventional_npdm
```

In this mode you can simply put the ``tran_onepdm`` keyword to get the transition 1pdm, for each pair of states, no matter they have the same irrep or not. A small bug fix https://github.com/block-hczhai/block2-preview/commit/e7605221761c8421589c05884293304a2fb8608e is required to make the above input file work.

### Using the input file interface (complicated case)

The above case is simple, but does not allow you to refine the states. The following explains how you can compute states for different irreps in separate runs and then compute transition 1pdm between them.

> Would I need to change the "prefix" argument to give them the same scratch directory

Yes

> and run them one-by-one, with "mps_tags" and then do "restart_tran_onepdm"?

You need to set different mps_tags for each state_average MPS. Note that one state-average MPS may have multiple roots, but it only needs one tag. For example, "mps_tags KET0" for irrep 1 and "mps_tags KET1" for irrep 2. After the state-average DMRG, you need a new input file with the keyword "restart_copy_mps" and "split_states" to tell the code to split the state-average MPS into multiple individual states. The individual MPSs will have tags "KET0-0", "KET0-1", etc.
Then you use a new input file with "restart_tran_onepdm", "conventional_npdm" and "mps_tags KET0-0 KET0-1 KET1-0 KET1-1" to get the transition 1pdms. Some example usage of "split_states" can be found in https://block2.readthedocs.io/en/latest/user/advanced.html#time-evolution.

### Using the python interface

> However, if I want to compute multiple states in one irrep (e.g. nroots > 1 in ket1) and then compute the TDM between the ground state and the different computed excited states is that possible? Furthermore, how does / can one do state specific DMRG in the python interface?

See the following example script.

```python3
from pyscf import gto, scf, lib, mcscf
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyblock2._pyscf.ao2mo import integrals as itg
import numpy as np
import os

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, stack_mem=4 << 30, n_threads=8)

lib.param.TMPDIR = os.path.abspath(driver.scratch)

if not os.path.exists(lib.param.TMPDIR):
    os.mkdir(lib.param.TMPDIR)
    
mol = gto.M(atom='C 0 0 0; C 0 0 1.2425', basis='cc-pvdz', symmetry='d2h', verbose=3)
mf = scf.RHF(mol).run()
mc = mcscf.CASCI(mf, 8, 8)

ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf, mc.ncore, mc.ncas, g2e_symm=8)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=0)

# state average
target = driver.bw.SX(n_elec, spin, 0) # A1g (XOR convention)
ket0 = driver.get_random_mps(tag="KET0", bond_dim=200, nroots=3, target=target)
energies = driver.dmrg(mpo, ket0, n_sweeps=10, bond_dims=[200] * 10, noises=[1e-5] * 4 + [0],
    thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
print('CASCI/DMRG  state-average energies (A1g) = %20.15f %20.15f %20.15f' % tuple(energies))

target = driver.bw.SX(n_elec, spin, 2) # B2g (XOR convention)
ket1 = driver.get_random_mps(tag="KET1", bond_dim=200, nroots=2, target=target)
energies = driver.dmrg(mpo, ket1, n_sweeps=10, bond_dims=[200] * 10, noises=[1e-5] * 4 + [0],
    thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
print('CASCI/DMRG  state-average energies (B2g) = %20.15f %20.15f' % tuple(energies))

# split into individual mpss
ket0s = [driver.split_mps(ket0, ir, tag='KET0.%d' % ir) for ir in range(ket0.nroots)]
ket1s = [driver.split_mps(ket1, ir, tag='KET1.%d' % ir) for ir in range(ket1.nroots)]

# refine each mps
energies = []
for ir in range(ket0.nroots):
    ener = driver.dmrg(mpo, ket0s[ir], n_sweeps=10, bond_dims=[500] * 10, noises=[1e-5] * 4 + [0],
        proj_mpss=[pj.deep_copy("PJ.%d" % ip) for ip, pj in enumerate(ket0s[:ir])], proj_weights=[10] * ir,
        thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
    energies.append(ener)
print('CASCI/DMRG state-specific energies (A1g) = %20.15f %20.15f %20.15f' % tuple(energies))

energies = []
for ir in range(ket1.nroots):
    ener = driver.dmrg(mpo, ket1s[ir], n_sweeps=10, bond_dims=[500] * 10, noises=[1e-5] * 4 + [0],
        proj_mpss=[pj.deep_copy("PJ.%d" % ip) for ip, pj in enumerate(ket1s[:ir])], proj_weights=[10] * ir,
        thrds=[1e-9] * 10, tol=1E-12, cutoff=1E-24, iprint=0)
    energies.append(ener)
print('CASCI/DMRG state-specific energies (B2g) = %20.15f %20.15f' % tuple(energies))

# transition 1PDM
np.set_printoptions(precision=3, suppress=True)
for ir in range(ket0.nroots):
    for it in range(ir, ket0.nroots):
        dm1 = driver.get_conventional_1pdm(ket=ket0s[ir], bra=ket0s[it])
        print('Transition 1PDM (%d A1g <- %d A1g) =\n' % (it, ir), dm1)
for ir in range(ket0.nroots):
    for jr in range(ket1.nroots):
        dm1 = driver.get_conventional_1pdm(ket=ket0s[ir], bra=ket1s[jr])
        print('Transition 1PDM (%d B2g <- %d A1g) =\n' % (jr, ir), dm1)
```

**Comment by hczhai** [comment]
> and then following the info in the "Load MPS for Density Matrix Calculation" of the documentation, but I have run into several issues trying to work this approach as well.

The input file shown in "Load MPS for Density Matrix Calculation" of the documentation may fail due to the missing ``conventional_npdm`` keyword. The documentation is now updated with https://github.com/block-hczhai/block2-preview/commit/ecacf8fdd7b7ea1838d2d41f621bc8bb0fb768d2.
