### ISSUE TITLE
Different energy for re-evaluation after DMRG run

### ISSUE THREAD

**Issue by yannra** [block-hczhai/block2-preview#53]
Hi all,
I ran into a rather strange behavior when running DMRG with block2 - this might point towards a bug or a lack of understanding how the code works on my end so I thought I'd quickly reach out via this channel.

In short the problem is as follows: Having run DMRG for a molecular system, a re-evaluation of the energy with the optimized state gives a different (worse) energy than the energy obtained in the DMRG run. This seems to be a bit setup dependent but the minimal example below should explain what is going on. The agreement between the energies improves as the bond dimension of the MPS is allowed to be larger - but still, I would expect the two energy values to agree regardless of what bond dim is chosen (or am I wrong here?).

This is the minimal example:

```python
from pyscf import gto, scf, ao2mo

from pyblock2.driver.core import DMRGDriver, SymmetryTypes

import numpy as np


# Set up H chain (8 atoms, minimal basis set)
dist = 3.0
norb = 8

mol = gto.Mole()

mol.build(
    atom=[("H", (x, 0.0, 0.0)) for x in dist * np.arange(8)],
    basis="sto-6g",
    symmetry=True,
    unit="Bohr",
)

# We are running the calculation in a canonical basis, which is set up here.
myhf = scf.RHF(mol)
ehf = myhf.scf()
basis = myhf.mo_coeff

h1 = np.linalg.multi_dot((basis.T, scf.hf.get_hcore(mol), basis))
h2 = ao2mo.restore(1, ao2mo.kernel(mol, basis), basis.shape[0])


# Set up the DMRG calc
mps_solver = DMRGDriver(symm_type=SymmetryTypes.SU2)
mps_solver.initialize_system(h1.shape[0], n_elec=np.sum(mol.nelec))
mpo = mps_solver.get_qc_mpo(h1e=h1, g2e=h2, iprint=1, reorder=None)

ket = mps_solver.get_random_mps("KET", bond_dim=50, nroots=1)

# Run DMRG
en = mps_solver.dmrg(mpo, ket, n_sweeps=100, iprint=1, bond_dims=[50])

print("DMRG final energy: {}".format(en))

# Now re-evaluate the energy
print("Re-evaluated energy: {}".format(mps_solver.expectation(ket, mpo, ket)))
```

For my version of block2 (latest Pypi version) this gives the following result:

> DMRG final energy: -8.559546134243703
> Re-evaluated energy: -8.55220532772357

So there is a bit of a discrepancy between the two results which surprises me - and I'm not sure where this is coming from.
Could you maybe look into this and check if this is actually a bug? 

Thanks a lot and best wishes!
Yannic

**Comment by hczhai** [comment]
Hi Yannic,

Thanks for reporting the issue. This is because the (default) two-site DMRG sweep algorithm is not variational during a sweep (not a bug).

1. If you use ``mps_solver.dmrg(..., iprint=2)`` you will clearly see that during one sweep, you get different energies at different site. The energy at the middle site is normally lower (more accurate) and reported to be the ground state energy.
2. When you finish the sweep, the canonical center of MPS is at the boundary. So the energy you get from ``mps_solver.expectation(...)`` will match the energy printed in ``mps_solver.dmrg(..., iprint=2)`` at the last site of the last sweep, which will normally be slightly higher than the energy at the middle site of the last sweep.
3. One-site DMRG (namely, only optimize the tensor at one site at a time) with no noise is variational. This means if you run one-site DMRG with enough sweeps, even when bond dimension is small, you will get identical energies at the middle and boundary sites. The standard practice is switching from 2-site to 1-site when it is approaching to convergence. For example, you can do ``mps_solver.dmrg(n_sweeps=35, twosite_to_onesite=25)`` so the first 25 sweeps will be two-site, and the last ten sweeps will be one-site, and then you will see a better matching of the energies.
4. For more technical discussions see Sec. II A & B in [_JCP_ **142**, 034102 (2015)](https://doi.org/10.1063/1.4905329).

**Comment by yannra** [comment]
Hi Huanchen,
I see, this makes sense.
Many thanks for the very quick and detailed response (again)! I really appreciate the support.

Best wishes,
Yannic
