### ISSUE TITLE
Restart doesn't work after 2pdm are calculated

### ISSUE THREAD

**Issue by bogdanoff** [block-hczhai/block2-preview#6]
I found an issue with restart simple DMRG after 2pdm are calculated.
After one runs `twopdm` or `restart_twopdm` , `fullrestart` job gets a segfault at the `me.init_environments()` step with the following error:
```
python: /home/bogdanov/src/block2/src/pybind/../core/matrix_functions.hpp:307: static void block2::GMatrixFunctions<double>::multiply(const MatrixRef&, uint8_t, const MatrixRef&, uint8_t, const MatrixRef&, double, double): Assertion `a.n >= b.m && c.m == a.m && c.n >= b.n' failed.
python: /home/bogdanov/src/block2/src/pybind/../core/matrix_functions.hpp:307: static void block2::GMatrixFunctions<double>::multiply(const MatrixRef&, uint8_t, const MatrixRef&, uint8_t, const MatrixRef&, double, double): Assertion `a.n >= b.m && c.m == a.m && c.n >= b.n' failed.
```

interestingly, calculations with two roots are not affected.
it also seems that `bmps.info.bond_dim` and `kmps.info.bond_dim` are not set properly. I don't know if that matters, but they are equal to `startM` rather then `maxM` as I would expect.

Minimal example inputs:
[restart_bug.zip](https://github.com/block-hczhai/block2-preview/files/8050387/restart_bug.zip).
Running 
```
block2main 01.inp > 01.out
block2main 02.inp > 02.out
```
should reproduce the error.
If one comments out `twopdm` line in `01.inp`, calculation from `02.inp` runs normally.

**Comment by hczhai** [comment]
Thanks for pointing out the issue and providing the example.
It should now be fixed in https://github.com/block-hczhai/block2-preview/commit/4a9045f8d930f9b50ac525e457ddf2f6368c6b57 (the pip package is not yet updated).
When restarting, the MPS can have many possible center site, canonical form, or 1dot/2dot. We have to carefully identity all these cases in the python driver. What you see is one case that we did not encountered before. Before adding this patch, you may also change the number of sweeps from even to odd in ``01.inp``, or remove the keyword ``onedot`` in ``02.inp`` to circumvent this issue.

**Comment by hczhai** [comment]
> it also seems that bmps.info.bond_dim and kmps.info.bond_dim are not set properly. I don't know if that matters, but they are equal to startM rather then maxM as I would expect.

This is because your testing system is too small, the actual MPS bond dimension (printed in ``01.out`` as ``Mmps = ...``) never arrives at ``startM = 250`` or ``maxM = 500``. So there is no accuracy loss in computing 2pdm with M = 250.

For realistic cases (larger problems), the actual MPS bond dimension should arrive at the ``maxM`` after some sweeps. Then the ``kmps.info.bond_dim`` will be updated with the actual MPS bond dimension or ``maxM`` as expected. Then you should see ``kmps.info.bond_dim`` not equal to ``startM``.

**Comment by bogdanoff** [comment]
Thank you very much for the quick fix!
