### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by mfdgroot** [block-hczhai/block2-preview#65]
Hi Huanchen,

I'm trying to save an MPS through the get_mps_from_csf_coefficient function in python mode and then load it again through the inputfile mode.
I get an error in https://github.com/block-hczhai/block2-preview/blob/da9d655758b360ddcf62b05500c3364430109ab3/pyblock2/driver/block2main#L1454 with message

```
mps_info.bond_dim = max_bdim
    ^^^^^^^^^^^^^^^^^
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: block2.su2.MPSInfo, arg0: int) -> None
```

I can also reproduce it by using the python interface and trying to save an MPS with bond_dim = 2^32, which does not happen with 2^32-1.
```
mps = driver.get_mps_from_csf_coefficients(dets, vals, tag="CMPS", dot=2)
mps.info.bond_dim= 4294967296
mps.info.save_data(scratchdir + "/node0/%s-mps_info.bin" % mps.info.tag)                                                                     
```

To be clear: I don't need such high bond dimensions, they are automatically set when reading and then overrun the integer.
Can I somehow make the MPSInfo expect a long int?

**Comment by hczhai** [comment]
Hi Matthias,

Thanks for reporting this problem. It should be fixed in this commit: https://github.com/block-hczhai/block2-preview/commit/b86276b64e23f4088f0345be1624f298181f5576 and later in version [p0.5.3rc2](https://github.com/block-hczhai/block2-preview/releases/tag/p0.5.3rc2). As you already noted, the actual MPS bond dimension is not that large, so as long as the MPS (constructed from CSF) has a correct number for its actual bond dimension, it should be good.

When you load an MPS (created in the python script) using the input file interface, there are a few caveats:

1. The keyword ``hf_occ integral`` should not present in the input file. This is to ensure that the input file interface will find the ``*-mps_info.bin`` under ``<driver.scratch>`` rather than ``<driver.scratch>/node0``.
2. The keyword ``noreorder`` should present in the input file since in the python script by default we do not do any orbital reordering but in the input file interface, the default orbital strategy is ``fiedler``.
3. In the input file, we set the scratch dir as ``prefix <scratch>`` where ``<scratch>`` should be the same as ``driver.scratch`` in the python script.
4. In the input file, we need ``mps_tags <tag>`` where ``<tag>`` should match the MPS tag in the python script.
5. In order to match the Hamiltonian integrals, one can use ``driver.write_fcidump`` to write the ``FCIDUMP`` file and then load it in the input file interface.

The following is an example for this task. Python script part:

```python3
import numpy as np
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyscf import gto, scf

bond_dims = [250] * 4 + [500] * 4
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 8

mol = gto.M(atom="N 0 0 0; N 0 0 1.1", basis="sto3g", symmetry="d2h", verbose=0)
mf = scf.RHF(mol).run(conv_tol=1E-14)
ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf,
    ncore=0, ncas=None, g2e_symm=8)
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, n_threads=4)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)
driver.write_fcidump(h1e=h1e, g2e=g2e, ecore=ecore, filename='FCIDUMP')

mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=0)
ket = driver.get_random_mps(tag="GS", bond_dim=250, nroots=1)
energy = driver.dmrg(mpo, ket, n_sweeps=20, bond_dims=bond_dims, noises=noises,
    thrds=thrds, iprint=1)
print('DMRG energy = %20.15f' % energy)

csfs, coeffs = driver.get_csf_coefficients(ket, cutoff=0.05, iprint=1)
mps = driver.get_mps_from_csf_coefficients(csfs, coeffs, tag="CMPS", dot=2)
```

Input file part (can be executed using ``block2main dmrg.conf`` where ``dmrg.conf`` is the input file name):
```
sym d2h
orbitals FCIDUMP
schedule default
maxM 500
maxiter 30
num_thrds 16
fullrestart
prefix ./tmp
mps_tags CMPS
noreorder
```

**Comment by mfdgroot** [comment]
Thanks Huanchen.
I only had time to try the solution now, the problem seems solved.
