### ISSUE TITLE
Loading of mps_info.bin sometimes fails

### ISSUE THREAD

**Issue by cvjjm** [block-hczhai/block2-preview#67]
I am running block2 via the pyscf interface and am experiencing intermitted crashes of `block2main` that look like this;
```
SPIN ADAPTED - REAL DOMAIN - DOUBLE PREC
qc mpo type =  QCTypes.Conventional
 UseMainStack = 0 MinDiskUsage = 1 MinMemUsage = 0 IBuf = 0 OBuf = 0
 FPCompression: prec = 1.00e-16 chunk = 1024
 IMain = 0 B / 5.87 GB DMain = 0 B / 30.2 GB ISeco = 0 B / 2.51 GB DSeco = 0 B / 45.3 GB
 OpenMP = 1 TBB = 0 MKL = GNU 2021.0.4 SeqType = Tasked MKLIntLen = 4
 THREADING = 2 layers : Global | Operator BatchedGEMM 
 NUMBER : Global = 32 Operator = 32 Quanta = 0 MKL = 1
 COMPLEX = 1 SINGLE-PREC = 1 KSYMM = 0
using fiedler reorder =  [ 6  8  9  7  4  5 12 10  2  0  3  1 11]
read integral finished 0.05726950988173485
integral sym error =            0
MinMPOMemUsage =  False
full restart
Traceback (most recent call last):
  File "/fs/home/cvjjm/.conda/envs/asf/bin/block2main", line 1360, in <module>
    mps_info.load_data(scratch + "/mps_info.bin")
RuntimeError: MPSInfo:load_data on '/tmp/tmpzgma0uvm/node0/mps_info.bin' failed.
MPI FINALIZE: rank 0 of 1
srun: error: tmsa019: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=337663.7
```
Simply running the same computation again has so far always resolved the issue for me. I cannot systematically reproduce the issue but I had put some debug code into `block2main` which showed me that when the crash happens `mps_info.bin` exists but is an empty file. 

I suspect that this may be cause by `mps_info.bin` from before the restart not yet being fully flushed to disk.

Maybe this can be solved easily by simply making sure (either inside the C code or on the python side) that data written by `mps_info.save_data()` is fully flushed to disk before `mps_info.load_data()` is called?

**Comment by hczhai** [comment]
Hi, thanks for reporting the problem. It seems to be a filesystem/computer dependent problem.

1. If you are working on a supercomputer shared by many people, it is not a good idea to set the scratch folder under ``/tmp``. You may try change the folder to the scratch dir, project dir, or current dir, and see if you can get the same problem. The ``/tmp`` directory is not designed for writing scratch files.
2. Since you are doing a restarting calculation, when you say "simply running the same computation again has so far always resolved the issue for me", does this mean you run the "restarting" job again (instead of the previous job that generates the MPS)?
3. The problem seems to be a feature/setting of your filesystem. There is nothing I can do to change the ``block2`` code. But in your job submitting script, before you invoke ``block2main ...``, you can add the following code to wait until ``mps_info.bin`` is not an empty file:

```bash
#!/bin/bash

while [ ! -s "${SCRATCH}/node0/mps_info.bin" ]; do
    echo waiting mps_info.bin ...
    sleep 2
done
```

**Comment by cvjjm** [comment]
Thanks for the prompt response! 

1. This is on an HPC system and I have experienced this on /tmp, /fs/scratch (the intended scratch location on this cluster) and on /fs/nvme (a fast nvme local storage which some of the queues have). For multi node jobs I am of course using /fs/scratch, which is the only one of these file systems that is fast and synced between nodes.
2. I mean completely restarting my program. I am using DMRGCI from pyscf.dmrgscf and have some additional wrapper code that makes sure that e.g. casci.fcisolver.scratchDirectory is a fresh temporary directory when my pythong program is re-run.
3. I don't think I agree with this entirely. While I do agree that the file system definitely has something do do with it, But there is simply no code in block2main that would force the operating system to actually flush outputs to disk before block2main exits, nor is there any code in https://github.com/pyscf/dmrgscf/blob/master/pyscf/dmrgscf/dmrgci.py that would ensure that this happens between calls to `executeBLOCK()`. I speculate that this is causing the issue for me. As I wrote above, I can get rid of the problem by putting `os.sync()` after every `mps_info.save_data(...)` call in `block2main`.

I will try to alternatively see what happens when prepeding `sync &&` to the `MPIPREFIX` of `pyscf/dmrgscf/settings.py`.

**Comment by hczhai** [comment]
> As I wrote above, I can get rid of the problem by putting os.sync() after every mps_info.save_data(...) call in block2main.

``os.sync()`` can be expensive due to the relatively slow disk speed. See https://github.com/python/cpython/issues/102184 . So I do not think it is a good idea to do this by default in an operating system (with correct settings) that does not require it. Probably you should add it after the ``check_call`` in https://github.com/pyscf/dmrgscf/blob/master/pyscf/dmrgscf/dmrgci.py#L949 rather than "after **every** ``mps_info.save_data(...)`` call in ``block2main``".

> I am running block2 via the pyscf interface and am experiencing intermitted crashes

I see evidences that you are using an old version of ``block2``. Could you please update your ``block2`` version and see if the problem can be fixed.
