### ISSUE TITLE
Orbital ordering in pyblock2

### ISSUE THREAD

**Issue by xsun21** [block-hczhai/block2-preview#71]
Hi @hczhai,

I'm trying to solve an Anderson impurity model(with spin-orbit coupling considered) by DMRG. I consider 3 impurity orbitals and 15 bath orbitals(with spin considered there are 36 sites and the one-particle matrix is 36 by 36). There're both one-body(include soc) and two-body terms inside the impurity. The bath part is noninteracting and diagonalized(the bath part of the one-particle matrix is diagonal). Long-range hoppings exist between the impurity part and bath part. I list these terms at the end of this letter.

I use python interface to calculate this model under symmetrytype SGFCPX, however I find the algorithm is not quite efficient (I need to increase the bond dimension to around 5000 to get the desired accuracy)for this relatively small system. My question is that will the choice of orbital ordering play an important role in this problem? When I input the one-body and two-body terms and build the mpo with ### _driver.get_mpo_###, the default order of mpo is just ###_b.finalize(adjust_order = True)_###, what is the ordering used here? I know there're several choices of ordering in your codes(e.g. fiedler, gaopt...), how can I use these orderings in the codes, are they for mpo or mps? I'm also curious are there any choices of single-partice basis tranformations here?

Thanks!!

Here's the codes I use:

     driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SGFCPX, stack_mem= 100 << 30, n_threads=self.nthreads)
     driver.initialize_system(n_sites=self.ntot, n_elec=self.ntot//2)
        b = driver.expr_builder()
        for i in range(self.ntot):
            for j in range(self.ntot):
                if abs(H1E[i,j])>1e-6:
                    b.add_term("CD", [i,j], H1E[i,j])
       for i in range(self.nimp):
           for j in range(self.nimp):
               for k in range(self.nimp):
                   for l in range(self.nimp):
                       if abs(V2E[i,k,j,l])>1e-6:
                           b.add_term("CCDD", [i,j,l,k], 0.5*V2E[i,k,j,l])
       mpo = driver.get_mpo(b.finalize(), iprint=0)
       self.ket = driver.get_random_mps(tag="KET", bond_dim=self.maxM, nroots=1)
       noises = [1e-4]*2 + [1e-5]*2 + [0]
       bond_dims = [self.maxM] * 40
       thrds = [1e-10]*20 + [1e-11]*20
       energies = driver.dmrg(mpo, self.ket, n_sweeps=40, bond_dims=bond_dims, noises=noises, thrds=thrds, tol=1e-8, cutoff=0, iprint=1)

The one-body matrix of the impurity part (6 by 6):
[[-5.8050202724+0.j.   0.+0.j    0.+0.j   0. -0.05j    0. +0.j    0.05+0.j  ]
 [ 0.+0.j    -5.8050202724+0.j    0.-0.05j    0.+0.j   -0.05 +0.j    0.+0.j  ]
 [ 0.+0.j    0.+0.05j    -5.6934342724+0.j    0.+0.j    0.-0.05j   0.+0.j  ]
 [ 0.+0.05j    0.+0.j    0.+0.j    -5.6934342724+0.j    0.+0.j    0.+0.05j]
 [ 0.+0.j   -0.05+0.j   0.+0.05j    0.+0.j   -5.6934342724+0.j    0.+0.j  ]
 [ 0.05+0.j    0.+0.j    0.+0.j    0.-0.05j   0.+0.j   -5.6934342724+0.j  ]]

Hoppings bettwen impurity and bath (6 by 30):
[[ 0.0031889572-0.j            0.6449301612-0.j
   0.000000007 +0.0000000002j  0.0000006233+0.0000000197j
  -0.0000000125+0.000000005j  -0.0000000316+0.0000000125j
   0.0005820393-0.j           -0.3011300912+0.j
  -0.0000000025-0.0000000001j  0.000000149 +0.0000000085j
  -0.0000000001+0.0000000001j -0.000000008 +0.0000000107j
  -0.0862464252+0.j           -0.0333239748+0.j
   0.000000008 -0.0000000048j  0.0000000092-0.0000000056j
  -0.0000000026-0.0000000002j  0.0000000227+0.0000000014j
  -0.0000001187+0.0000000025j -0.0000001453+0.000000003j
   0.0000000303-0.j            0.0000013653-0.0000000015j
   0.1868864111+0.j            0.0063055848+0.j
  -0.0000001056-0.0000000359j  0.0000000561+0.0000000191j
   0.0000000141-0.0000000003j -0.0000005258+0.0000000117j
  -0.2439150715-0.j            0.0133315423+0.j          ]
 [-0.6449292237+0.0010996181j  0.0031889526-0.0000054372j
  -0.000000283 -0.0000005558j  0.0000000032+0.0000000063j
   0.000000005 -0.0000000336j -0.000000002 +0.0000000133j
  -0.3011272632-0.0013050719j -0.0005820338-0.0000025225j
   0.0000001415-0.0000000473j  0.0000000023-0.0000000008j
  -0.0000000017+0.0000000133j  0.          -0.0000000001j
  -0.0333233998-0.0001957628j  0.086244937 +0.0005066574j
   0.0000000084-0.0000000067j -0.0000000073+0.0000000058j
   0.0000000218-0.0000000065j  0.0000000025-0.0000000007j
-0.0000001252-0.0000000739j  0.0000001023+0.0000000604j
  -0.0000013441-0.0000002395j  0.0000000298+0.0000000053j
   0.0063053822+0.0000505456j -0.1868804067-0.001498082j
  -0.0000000191-0.0000000561j -0.0000000359-0.0000001056j
  -0.0000000456-0.000000524j  -0.0000000012-0.0000000141j
  -0.0133312371-0.0000902129j -0.243909487 -0.0016505439j  ]
 [ 0.0000000005+0.0000000002j  0.0000001064+0.0000000462j
  -0.00141646  -0.0000741387j -0.1258750917-0.0065887953j
  -0.0471416619+0.0711471246j -0.1187306269+0.1791894293j
   0.0000000001-0.0000000001j -0.0000000611+0.0000000652j
   0.0013349067+0.0000366081j -0.0809217842-0.0022192717j
  -0.0005901101-0.0019358359j -0.0569254639-0.1866736089j
  -0.0000000229+0.0000000057j -0.0000000088+0.0000000022j
   0.0387811693+0.0656407784j  0.0449372201+0.0760606175j
   0.000970826 +0.0000253416j -0.0084694868-0.0002211222j
   0.031293747 +0.1066442248j  0.0383042385+0.1305313169j
  -0.0005269029-0.0000107965j -0.0237671609-0.0004865415j
   0.0000002287+0.0000001528j  0.0000000077+0.0000000052j
  -0.1123289518-0.1103172593j  0.0597247499+0.0586560891j
  -0.0009443612+0.0000388031j  0.0351265497-0.0014432957j
   0.0000000134+0.0000000654j -0.0000000007-0.0000000036j  ]
[-0.0000001065-0.000000046j   0.0000000005+0.0000000002j
   0.0548617669+0.1134818421j -0.0006173543-0.0012770015j
  -0.0956015364-0.1925257581j  0.037958265 +0.0764422707j
  -0.0000000614+0.0000000649j -0.0000000001+0.0000000001j
  -0.0759722933+0.0279547893j -0.0012532611+0.0004611491j
  -0.1410839061-0.1348438981j  0.0014631613+0.0013981607j
  -0.0000000089+0.0000000022j  0.0000000229-0.0000000056j
   0.0546202338+0.0694348702j -0.0471375709-0.0599227874j
  -0.0080250176+0.0027166438j -0.000919897 +0.0003114011j
  -0.0361316496+0.1311493166j  0.0295187444-0.1071491115j
   0.0233081688+0.0046738516j -0.0005166919-0.0001036221j
   0.0000000077+0.0000000052j -0.0000002275-0.0000001546j
   0.0101052525-0.0830991321j  0.0190068656-0.1562895628j
   0.0037029338+0.0349606809j  0.0000994995+0.0009399411j
   0.0000000007+0.0000000036j  0.0000000129+0.0000000655j]
 [-0.0000000011-0.j           -0.0000002303-0.000000001j
   0.0025988348+0.0001360295j  0.2309479696+0.0120886779j
  -0.0256938753+0.0387777133j -0.0647123913+0.0976646188j
  -0.0000000003+0.j            0.0000001374-0.0000000008j
  -0.0032179501-0.0000882505j  0.1950712238+0.0053498205j
  -0.0002447971-0.000803047j  -0.0236144951-0.0774381746j
   0.000000025 -0.0000000001j  0.0000000096-0.j
  -0.0028342767-0.0047973908j -0.0032841698-0.0055589045j
   0.013284653 +0.0003469717j -0.1158953723-0.0030269691j
0.0042359717+0.0144352725j  0.0051848983+0.0176686641j
   0.0038926086+0.0000796675j  0.1755844149+0.0035937869j
  -0.000001287 -0.0000000044j -0.0000000434-0.0000000001j
  -0.0221550832-0.0217581707j  0.011779733 +0.011568955j
   0.0047882148-0.0001967864j -0.1780972118+0.0073181847j
   0.0000003577+0.0000000003j -0.0000000195-0.j          ]
 [ 0.0000002303+0.0000000006j -0.0000000011-0.j
  -0.1006570386-0.2082096787j  0.0011326785+0.0023429644j
  -0.0521061983-0.1049333478j  0.0206885884+0.0416637442j
   0.0000001374-0.0000000002j  0.0000000003-0.j
   0.1831399187-0.0673882323j  0.0030211276-0.0011116533j
  -0.0585261076-0.0559375481j  0.0006069641+0.0005800007j
   0.0000000096+0.j           -0.000000025 -0.0000000001j
  -0.0039918868-0.0050746604j  0.003445017 +0.0043794733j
  -0.1098135879+0.0371735902j -0.0125875191+0.0042610706j
  -0.0048907592+0.0177523338j  0.0039956265-0.0145036694j
  -0.1721933916-0.0345287847j  0.0038174356+0.0007654865j
  -0.0000000434-0.0000000005j  0.0000012869+0.0000000147j
   0.0019931272-0.0163899645j  0.0037488005-0.0308255566j
  -0.018774332 -0.177256012j  -0.0005047318-0.004765596j
   0.0000000195+0.0000000001j  0.0000003577+0.0000000027j. ]]
One-body matrix for the bath (30 by 30):
Diag[ -1.795, -1.795, -1.438, -1.438, -1.438, -1.438, -0.222, -0.222, -0.130, -0.130, -0.130, -0.130, -0.003, -0.003, 0.008, 0.008, 0.008, 0.008, 0.163, 0.163, 0.163, 0.163, 0.168, 0.168, 1.00, 1.00, 1.00, 1.00, 1.06, 1.06 ]

**Comment by hczhai** [comment]
Hi, thanks for your interest in using this code.

> I need to increase the bond dimension to around 5000

Normally you need a schedule to increase the MPS bond dimension gradually during the DMRG sweeps, rather than using a constant big bond dimension for all sweeps. So ``bond_dims = [self.maxM] * 40`` is not a good idea. Please check https://block2.readthedocs.io/en/latest/tutorial/energy-extrapolation.html#The-Normal-Schedule to see what is a better schedule.

> I list these terms at the end of this letter.

I do not find the V2E data in your post. So I cannot run your script. You may attach your H1E and V2E as numpy files  (using ``numpy.save``) so that I can do some tests on your case. You may also attach the output file (the ``iprint=1`` and ``iprint=0`` should be all changed to ``iprint=2`` to include more details). ``maxM = 500`` is okay, we just need to see the behavior.

> My question is that will the choice of orbital ordering play an important role in this problem?

It depends on your integrals (H1E and V2E) but V2E is missing so I cannot judge.

> When I input the one-body and two-body terms and build the mpo with ### driver.get_mpo###, the default order of mpo is just ###b.finalize(adjust_order = True)###, what is the ordering used here?

The ``adjust_order=True`` is for some technical details in the MPO building algorithms, so it does not affect the "orbital ordering". And normally one should always set ``adjust_order=True``. This means the default ordering is "no reordering", meaning that the first site/orbital in DMRG corresponds to the first orbital index in your H1E / V2E, and so forth.

> I know there're several choices of ordering in your codes(e.g. fiedler, gaopt...), how can I use these orderings in the codes

For ``fiedler`` you can do

```python3
idx = driver.orbital_reordering(H1E, V2E)
H1E = H1E[idx][:, idx]
V2E = V2E[idx][:, idx][:, :, idx][:, :, :, idx]
```

For ``gaopt`` you can do

```python3
import numpy as np
import block2 as b2
h1e, g2e = H1E, V2E

xmat = np.abs(np.einsum("ijji->ij", g2e, optimize=True))
kmat = np.abs(h1e) * 1e-7 + xmat
kmat = b2.VectorDouble(kmat.ravel())
idx = b2.OrbitalOrdering.fiedler(len(h1e), kmat)

opts = dict(n_generations=10000, n_configs=len(h1e) * 2,
    n_elite=8, clone_rate=0.1, mutate_rate=0.1
)
n_tasks = 64
idxs = []
for i_task in range(0, n_tasks):
    b2.Random.rand_seed(1234 + i_task)
    idx = b2.OrbitalOrdering.ga_opt(len(h1e), kmat, **opts)
    f = b2.OrbitalOrdering.evaluate(len(h1e), kmat, idx)
    idx = tuple(idx)
    idxs.append(idx)
idx = sorted(list(set(idxs)))[0]
H1E = H1E[idx][:, idx]
V2E = V2E[idx][:, idx][:, :, idx][:, :, :, idx]
```

One of these can be done to reorder the indices in your integrals before you do ``b = driver.expr_builder()``. Note that H1E should have shape ``(ntot, ntot)`` and V2E should have shape ``(ntot, ntot, ntot, ntot)`` to make this work.

> are they for mpo or mps?

This will affect the MPO only. The initial MPS is random, so it does not have orbital ordering dependence (at least for your case). But after doing DMRG, the optimized MPS will have orbital ordering dependence.

> I'm also curious are there any choices of single-particle basis transformations here?

We do not automatically apply any single-particle basis transformations. If you need this, you can do it yourself by transforming your ``H1E`` and ``V2E`` before you give it to ``DMRGDriver``. Of course you can first use the "default" orbital and do a small bond dimension DMRG, then compute the 1pdm. From the 1pdm you can get the "DMRG natural orbitals" and then you can use this to transform your ``H1E`` and ``V2E`` and redo DMRG. But whether this is a better orbital choice is another problem.

**Comment by xsun21** [comment]
Thanks so much for your detailed response, which is very helpful for my problem.

The two orderings work very well in my case, which reduce the bond dimension to around 1000. I find gaopt works little better for my problem, was wondering if you use the same correlation matrix for both methods? Just curious would that derived by quantum mutual information generally behave better?

I also tried natural orbital by diagonalizing the bath 1pdm, which even makes the accuracy worse when ordering is performed. Maybe because the dimension of MPO increases by doing this.

**Comment by hczhai** [comment]
Thanks for feedback.

> I find gaopt works little better for my problem, was wondering if you use the same correlation matrix for both methods?

The scripts that I provided in the previous reply used the exchange integral $K_{ij}$ (``kmat``) as the cost function.

> Just curious would that derived by quantum mutual information generally behave better?

I have updated the ``block2`` documentation to include a section on orbital reordering, and added the support for computing orbital mutual information in the ``SGFCPX`` mode (https://github.com/block-hczhai/block2-preview/commit/2710e64533a9d4451ee939f87e84119df2a79ac1). These will allow you to first compute the mutual information using a small bond dimension MPS (without orbital reordering). Then you can use the computed mutual information (instead of the exchange integral) as the cost function to get a orbital reordering, and finally you can use reordered integrals to redo the DMRG. The example scripts for doing this are provided in the updated documentation: https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Orbital-Reordering

Note that in order to use this feature, you need to update ``block2`` to the latest version. If you install ``block2`` using ``pip``, you can update it using

```
pip install block2==0.5.3rc5 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/
```

**Comment by xsun21** [comment]
That makes sense, thank you!
