### ISSUE TITLE
Installing/building with intelpython and intel oneapi mkl+tbb

### ISSUE THREAD

**Issue by cvjjm** [block-hczhai/block2-preview#8]
I am trying to set up block2 in a containerized environment based on rockylnux with intelpython and intel oneapi mkl and tbb. I have verified with another OMP parallelization enabled program that the setup works in principle, but I am still struggling to get block2 to work (despite the useful information [in this issue](https://github.com/block-hczhai/block2-preview/issues/7)).

First, I tried a simple `pip install block2`. As expected this pulls in the `mkl-include`, `cmake`, `mlk`, `intel-openmp` python packages and block2 then uses these libraries rather than the ones provided by the system, as a simple ldd call shows:
```
        $ ldd /opt/intel/intelpython3/lib/python3.7/site-packages/block2.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffc5e19e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb82b06e000)
        libgomp-f7e03b3e.so.1.0.0 => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libgomp-f7e03b3e.so.1.0.0 (0x00007fb82ae57000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb82ac37000)
        libmkl_intel_lp64-7fce225f.so => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libmkl_intel_lp64-7fce225f.so (0x00007fb82a09f000)
        libmkl_core-fbf20eba.so => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libmkl_core-fbf20eba.so (0x00007fb825e9a000)
        libmkl_gnu_thread-22473446.so => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libmkl_gnu_thread-22473446.so (0x00007fb8245d5000)
        libmkl_avx2.so => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libmkl_avx2.so (0x00007fb820a2a000)
        libmkl_avx512.so => /opt/intel/intelpython3/lib/python3.7/site-packages/block2.libs/libmkl_avx512.so (0x00007fb81c877000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb81c4e2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb81c160000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb81bf48000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb81bb83000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb82f599000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb81b97f000)
```
This is of course not what I would ideally want but I expected it to at least work, However, while block2main, can be run and yields correct results, it only ever uses a single core even when starting it with, e.g., `export OMP_NUM_THREADS=4; block2main ...`. Just out of curiosity: Do you have any idea why?

Second, I tried to have pip compile block2 from source for me via `pip install block2 --no-binary :all:`. I expect this to still pull in the duplicate libraries but was hoping that then maybe somehow OMP would work. This leads to: `ERROR: Could not find a version that satisfies the requirement mkl==2019 (from block2) (from versions: none)`. The same happens when doing `pip install .` from a clone of the repository. Strangely, the above plain `pip install block2` installed `mkl-2019.0-py2.py3-none-manylinux1_x86_64.whl` just fine when instructed to install `mkl==2019`. Any idea why this is behaving differently? Why would pip be able to find a matching version and install it in one case but not the other?

I could finally make the `pip install .` from a git clone work by (i) manually doing `pip install pybind11` (without this the compilation fails because it cannot find some pybind11 header files - I see that pybind11 is listed under the `install_requires` but that does not seem to be enough) and (ii) removing the version pinning of mkl via `sed -i 's/mkl==2019/mkl/g' setup.py`. This then installs a 2022 mkl and openmp along with a 2021 tbb.
 
Third, I tried "the real thing" of compiling block2 manually from source via cmake against the system oneapi libraries. The first problem here was that cmake seems to look for tbb and related libraries in `$ENV{MKLROOT}/lib $ENV{MKLROOT}/lib/intel64 /usr/local/lib $ENV{TBBROOT}/lib` but with openapi they actually are in `$TBBROOT/lib/intel64/gcc4.8/`. This could be easily fixed by passing `-DTBB_LIB=$TBBROOT/lib/intel64/gcc4.8/libtbb.so -DTBB_LIBS_MALP=$TBBROOT/lib/intel64/gcc4.8/libtbbmalloc_proxy.so -DTBB_LIB_MAL=$TBBROOT/lib/intel64/gcc4.8/libtbbmalloc.so` to cmake. With this I could build the python extension manually via:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_MKL=ON -DBUILD_LIB=ON -DLARGE_BOND=ON -DUSE_KSYMM=OFF -DUSE_COMPLEX=ON -DUSE_SG=ON -DOMP_LIB=TBB -DTBB=ON -DTBB_LIB=$TBBROOT/lib/intel64/gcc4.8/libtbb.so -DTBB_LIBS_MALP=$TBBROOT/lib/intel64/gcc4.8/libtbbmalloc_proxy.so -DTBB_LIB_MAL=$TBBROOT/lib/intel64/gcc4.8/libtbbmalloc.so
cmake --build . --config Release -- --jobs=2
```
Looking with ldd:
```
        $ ldd /opt/intel/intelpython3/lib/python3.7/site-packages/block2.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007fc0dc17d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc0d7b73000)
        libmkl_intel_lp64.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so.2 (0x00007fc0d6cd3000)
        libmkl_core.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so.2 (0x00007fc0d291e000)
        libmkl_tbb_thread.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_tbb_thread.so.2 (0x00007fc0d05b8000)
        libmkl_avx2.so => /opt/intel/intelpython3/lib/libmkl_avx2.so (0x00007fc0cd65f000)
        libmkl_avx512.so => /opt/intel/intelpython3/lib/libmkl_avx512.so (0x00007fc0c9afc000)
        libtbb.so.12 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbb.so.12 (0x00007fc0c9884000)
        libtbbmalloc.so.2 => /opt/intel/intelpython3/lib/libtbbmalloc.so.2 (0x00007fc0c9629000)
        libtbbmalloc_proxy.so.2 => /opt/intel/intelpython3/lib/libtbbmalloc_proxy.so.2 (0x00007fc0c9425000)
        libstdc++.so.6 => /opt/intel/intelpython3/lib/libstdc++.so.6 (0x00007fc0dbffd000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc0c90a3000)
        libgcc_s.so.1 => /opt/intel/intelpython3/lib/libgcc_s.so.1 (0x00007fc0dbfe9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc0c8cde000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc0dbf53000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc0c8abe000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc0c88ba000)
```
I see that now the system mkl libraries were used - great (there is some shadowing of `libtbbmalloc*` but that should be fine)! 
Unfortunately now the library is no longer linked to `libgomp` at all and consequently, when I triy to load it I get `ImportError: /opt/intel/intelpython3/lib/python3.7/site-packages/block2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: GOMP_single_start`. This happens depite `libgomp` being installed in a standard location:
```
        $ ldconfig -p | grep gomp
        libgomp.so.1 (libc6,x86-64) => /lib64/libgomp.so.1
```
Unfortunately my knowledge of cmake is not sufficient to easily understand what is going wrong here. Any help would be highly appreciated!!! And apologies in case I am overlooking something obvious.

**Comment by hczhai** [comment]
Thanks for pointing out the issue. So there are several problems.

> it only ever uses a single core even when starting it with, e.g., ``export OMP_NUM_THREADS=4; block2main ...``. Just out of curiosity: Do you have any idea why?

The ``block2main`` script actually does not look at the environment variable ``OMP_NUM_THREADS``. You may need to set the keywords ``num_thrds`` and ``mkl_thrds`` to control the number of threads. The default of ``mkl_thrds`` is 1. In the most recent update I changed the default value of ``num_thrds`` to make it compatible with ``StackBlock``. The default ``num_thrds`` in ``StackBlock`` is 1. Before block2 version 0.4.12 the default ``num_thrds`` is 28. Now the default is 28 if there is no ``hf_occ integral`` in the input file, or 1 if there is ``hf_occ integral`` in the input file. This setting is strange but you may always explicitly set the ``num_thrds`` to avoid any confusion. [I have updated the documentation to indicate this default value.]

The total number of threads used is the product of ``num_thrds`` and ``mkl_thrds``. But based on our testing it is always better to set one of them to 1 (namely, avoid nested openmp). Additionally, the scheme ``num_thrds = n, mkl_thrds = 1`` should be better than ``num_thrds = 1, mkl_thrds = n`` for most cases. With ``mkl==2019`` and ``-DOMP_LIB=TBB`` and ``mkl_thrds`` not equal to 1, the actual total number of threads may occasionally be even larger than the total number of threads set.

>  I tried to have pip compile block2 from source for me via ``pip install block2 --no-binary :all:``. I expect this to still pull in the duplicate libraries but was hoping that then maybe somehow OMP would work. This leads to: ``ERROR: Could not find a version that satisfies the requirement mkl==2019 (from block2) (from versions: none)``. 

You can find an explanation of ``--no-binary`` option using ``pip install --help``. Basically, ``--no-binary :all:`` will avoid binary packages (namely, wheels) for all packages including the dependences of ``block2``. But some packages like ``mkl`` and ``pybind`` are not ordinary python packages that can be built from source. To solve your problem, here we only need to avoid binary packages for ``block2``, but we can accept binary packages for the dependences of ``block2``. So you may try ``pip install block2 --no-binary block2`` instead. [I have updated the README file to make it clearer how the ``--no-binary`` option should be used.]

> removing the version pinning of mkl via sed -i 's/mkl==2019/mkl/g' setup.py. This then installs a 2022 mkl and openmp along with a 2021 tbb.

The version pinning is mostly for binary installation, because the block2 binary is packaged with a partial copy of mkl 2019. If you install from source or manually, more recent version of mkl should also be okay. I have not tested the code with mkl 2022, but if it can finish a DMRG calculation then it is OK.

> The first problem here was that cmake seems to look for tbb and related libraries in ``$ENV{MKLROOT}/lib $ENV{MKLROOT}/lib/intel64 /usr/local/lib $ENV{TBBROOT}/lib`` but with openapi they actually are in ``$TBBROOT/lib/intel64/gcc4.8/``.

For this case your TBB path is a little bit too strange for us to include in CMake file. Beside your way to fix it, you may also modify the CMakeLists.txt file and add your custom path here https://github.com/block-hczhai/block2-preview/blob/v0.4.12/CMakeLists.txt#L322 (and similarly for Line 324 and 326) then it will be able to find the TBB library. (Namely, before the closing parenthesis at that line, add a space and then your path.)

> Unfortunately now the library is no longer linked to ``libgomp`` at all and consequently, when I triy to load it I get ImportError: ``/opt/intel/intelpython3/lib/python3.7/site-packages/block2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: GOMP_single_start``.

Here your ``libgomp`` is in ``/lib64`` but if you look at https://github.com/block-hczhai/block2-preview/blob/v0.4.12/CMakeLists.txt#L273 we did not include this in the searching path. So you can modify this Line 273 to help cmake find it. If you are compiling without the option ``-DOMP_LIB=TBB``, then you should modify Line 290 https://github.com/block-hczhai/block2-preview/blob/v0.4.12/CMakeLists.txt#L290.

Finally, as indicated in the section ``Manual Installation`` in the README, it is possible to use ``-DTBB=ON -DOMP_LIB=GNU`` rather than ``-DTBB=ON -DOMP_LIB=TBB``. The difference between the two is that the first one will link with ``mkl_gnu_thread`` and the second one will link with ``mkl_tbb_thread``. If you decided to always use the default ``mkl_thrds=1`` (recommended, as explained at the beginning), then whether ``mkl_gnu_thread`` or ``mkl_tbb_thread`` should not affect the speed of DMRG. ``libgomp`` is still required because you are using a ``gcc`` compiler and we used ``openmp`` to implement ``num_thrds`` (this is why there is a gomp undefined symbol error). If you use intel compiler you may need ``-DOMP_LIB=INTEL`` instead.

If you use ``-DOMP_LIB=GNU`` it may be possible to find a ``gomp`` automatically because there are some extra logic in CMake for finding it: https://github.com/block-hczhai/block2-preview/blob/v0.4.12/CMakeLists.txt#L291-L297.

**Comment by cvjjm** [comment]
Thanks for the extensive reply! Very useful! Explicitly setting `num_thrds` and `mkl_thrds` enables multi threading with the version installed via `pip install block2`. Also I can confirm that `pip install block2 --no-binary block2` works as well.

I haven't managed to run a self compiled version successfully.

With `-DTBB=ON -DOMP_LIB=GNU` compilation works, libgomp is correctly found and linked. With `-DTBB=ON -DOMP_LIB=INTEL` I needed to in manually add `-DOMP_LIB_NAME=/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64/libiomp5.so` otherwise `libiomp5` was not found. 

The output of ldd looks like this in the `GNU` case:
```
        linux-vdso.so.1 (0x00007f383a1ab000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3835ba3000)
        libgomp.so.1 => /opt/intel/intelpython3/lib/libgomp.so.1 (0x00007f383a176000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3835983000)
        libmkl_intel_lp64.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so.2 (0x00007f3834ae3000)
        libmkl_core.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so.2 (0x00007f383072e000)
        libmkl_gnu_thread.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_gnu_thread.so.2 (0x00007f382eb9b000)
        libmkl_avx2.so => /opt/intel/intelpython3/lib/libmkl_avx2.so (0x00007f382bc42000)
        libmkl_avx512.so => /opt/intel/intelpython3/lib/libmkl_avx512.so (0x00007f38280df000)
        libtbb.so.12 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbb.so.12 (0x00007f3827e67000)
        libtbbmalloc.so.2 => /opt/intel/intelpython3/lib/libtbbmalloc.so.2 (0x00007f3827c0c000)
        libtbbmalloc_proxy.so.2 => /opt/intel/intelpython3/lib/libtbbmalloc_proxy.so.2 (0x00007f3827a08000)
        libstdc++.so.6 => /opt/intel/intelpython3/lib/libstdc++.so.6 (0x00007f3839ffe000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3827686000)
        libgcc_s.so.1 => /opt/intel/intelpython3/lib/libgcc_s.so.1 (0x00007f3839fea000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f38272c1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3839f81000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f38270bd000)
```
And like this in the `INTEL` case (with `CC=/opt/intel/oneapi/mpi/latest/bin/mpicc` `CXX=/opt/intel/oneapi/mpi/latest/bin/mpicxx`):
```
        linux-vdso.so.1 (0x00007ffc2a9f9000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9dab9fa000)
        libiomp5.so => /opt/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libiomp5.so (0x00007f9dab5d9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9dab3b9000)
        libmkl_intel_lp64.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so.2 (0x00007f9daa519000)
        libmkl_core.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so.2 (0x00007f9da6164000)
        libmkl_intel_thread.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so.2 (0x00007f9da2a02000)
        libmkl_avx2.so => /opt/intel/intelpython3/lib/libmkl_avx2.so (0x00007f9d9faa9000)
        libmkl_avx512.so => /opt/intel/intelpython3/lib/libmkl_avx512.so (0x00007f9d9bf46000)
        libtbb.so.12 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbb.so.12 (0x00007f9d9bcce000)
        libtbbmalloc.so.2 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbbmalloc.so.2 (0x00007f9d9ba72000)
        libtbbmalloc_proxy.so.2 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbbmalloc_proxy.so.2 (0x00007f9d9b86d000)
        libmpicxx.so.12 => /opt/intel/oneapi/mpi/2021.5.1//lib/libmpicxx.so.12 (0x00007f9d9b64d000)
        libmpifort.so.12 => /opt/intel/oneapi/mpi/2021.5.1//lib/libmpifort.so.12 (0x00007f9d9b299000)
        libmpi.so.12 => /opt/intel/oneapi/mpi/2021.5.1//lib/release/libmpi.so.12 (0x00007f9d99a64000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9d99860000)
        libstdc++.so.6 => /opt/intel/intelpython3/lib/libstdc++.so.6 (0x00007f9dafe85000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9d994de000)
        libgcc_s.so.1 => /opt/intel/intelpython3/lib/libgcc_s.so.1 (0x00007f9dafe71000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9d99119000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9dafdd8000)
```
When trying to run `block2main` I get in both cases:
```
INTEL MKL ERROR: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_def.so.2: undefined symbol: mkl_sparse_optimize_csr_lu_smoother_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_def.so.2.
```
Any idea what could be causing this? Is that caused by me using mkl 2022?

**Comment by hczhai** [comment]
Thanks for your feedback. As shown in issue https://github.com/block-hczhai/block2-preview/issues/7, a common problem in manual installation and/or solving environments is that when you have multiple versions of a library, things can become complicated and you need to be careful about which one is actually used. In issue https://github.com/block-hczhai/block2-preview/issues/7, the problem is related to the mpi library, here for your case I guess the problem is related to the mkl library.

The output of ``ldd`` that you included is very helpful, from which I can see that, for both the ``icpc`` and ``g++`` cases, ``libmkl_core.so.2`` was linked to the Intel MKL 2022 one, but ``libmkl_avx2.so`` was linked to ``/opt/intel/intelpython3/lib/libmkl_avx2.so`` which must be the mkl library installed via ``pip install mkl== 2019``. So there are some inconsistencies. Ideally, I would expect that ``libmkl_avx2.so`` and ``libmkl_avx512.so`` are linked to ``/opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_avx2.so.2`` and ``/opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_avx512.so.2`` respectively.

All MKL versions before 2020 have a consistent library suffix ``.so``. But starting from oneapi 2020/2021 they use ``.so.1`` and for oneapi 2022 they use ``.so.2``. So to make sure it can find ``libmkl_avx2.so.2`` I changed the CMake file a little bit: https://github.com/block-hczhai/block2-preview/commit/bc425ea691de425e0ba8c059b4eca302ebe9665b Please apply this change to the ``CMakeLists.txt``.

Then, to solve the above problem, you may first ``pip uninstall mkl`` to remove that duplicate MKL, then manually rebuild your ``block2``. Hopefully now it can find the correct ``.so.2`` libraries to link. Then you can check whether things are okay using ``ldd``. Finally, you may install ``pip install mkl==2019`` back (if you still need it for some other reason) and this should not affect the manually built ``block2`` binary anymore.

I did not personally try intel mkl 2022 so it is possible that I missed something.

**Comment by cvjjm** [comment]
Your changes from bc4225ea and deactivating mkl in intelpython before building with `DOMP_LIB=INTEL` now results in a clean looking ldd output. No more linking against mkl libs from intelpython only mkl 2022 from oneapi:
```
linux-vdso.so.1 (0x00007ffd54f9b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f2136402000)
        libiomp5.so => /opt/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libiomp5.so (0x00007f2135fe1000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2135dc1000)
        libmkl_intel_lp64.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so.2 (0x00007f2134f21000)
        libmkl_core.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so.2 (0x00007f2130b6c000)
        libmkl_intel_thread.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so.2 (0x00007f212d40a000)
        libmkl_avx2.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_avx2.so.2 (0x00007f212a54e000)
        libmkl_avx512.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_avx512.so.2 (0x00007f21266dd000)
        libtbb.so.12 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbb.so.12 (0x00007f2126465000)
        libtbbmalloc.so.2 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbbmalloc.so.2 (0x00007f2126209000)
        libtbbmalloc_proxy.so.2 => /opt/intel/oneapi/tbb/2021.5.1/env/../lib/intel64/gcc4.8/libtbbmalloc_proxy.so.2 (0x00007f2126004000)
        libmpifort.so.12 => /opt/intel/oneapi/mpi/2021.5.1//lib/libmpifort.so.12 (0x00007f2125c50000)
        libmpi.so.12 => /opt/intel/oneapi/mpi/2021.5.1//lib/release/libmpi.so.12 (0x00007f212441b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2124217000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2123fff000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2123c3a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f213a7f4000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f21238a5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2123523000)
```
Side remark: Making this work was not entirely trivial as mkl cannot be easily uninstalled from intelpython. In the end I had to create an environment, install the `nomkl` package there, compile block2 into a wheel inside that environment, then delete the environment and install the wheel in the base environment, so that I can have both block2 and an mkl enabled numpy at the same time.

Unfortunately I am still getting the error
```
INTEL MKL ERROR: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_def.so.2: undefined symbol: mkl_sparse_optimize_csr_lu_smoother_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_def.so.2.
```
when running block2main.

I will try with an older mkl version and report back.

**Comment by cvjjm** [comment]
You were spot on! Thanks for your help with debugging this problem!
