### ISSUE TITLE
pdm traces

### ISSUE THREAD

**Issue by mfdgroot** [block-hczhai/block2-preview#97]
Dear @hczhai,

I've noticed an issue with pdms for systems with `S=/=0`.
The trace should be different for the different spins
`np.trace(pdm[0])=nalpha` and `np.trace(pdm[1])=nbeta`
but I get that 
`np.trace(pdm[0])=np.trace(pdm[1])=(nalpha+nbeta)/2`, which in my case is also non-integer.

I thought at first this would be due to singlet embedding, but I'm sure it's turned off:
`MPS =  CCRRRRRR 0 2 < N=11 S=5/2 PG=0 >`.
The same thing is happening when taking the 2pdm and constructing the 1pdm. I can get at the spin-summed ones but the spinful one has the same issue.
I'm using the input file interface with the `onepdm` or `twopdm` command.

Do you have an idea what could be going wrong?

**Comment by hczhai** [comment]
Hi, thanks for reporting the problem. It is the expected behavior. See https://github.com/block-hczhai/block2-preview/issues/58#issuecomment-1760033756.

You may also translate the converged spin-adapted MPS to a non-spin-adapted one (see https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Change-from-SU2-MPS-to-SZ-MPS or https://block2.readthedocs.io/en/latest/user/advanced.html#mps-transform) and then computing the pdms. Note that you will need the ``resolve_twosz`` keyword or the ``sz`` parameter (see https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.mps_change_to_sz) to pick up a particular $S_z$, since the spin-adapted MPS (before transformation) contains multiple $S_z$ components ($S_z = -S, -S+1, \cdots, S$).
